### ISSUE TITLE
[tema] Oppdatere kategorien Familie og barn

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#1]

**Comment by oystein-asnes** [comment]
Navnet på temaet endres til "Familie og barn". Dette samsvarer med regjeringen.no + det ivaretar eldre/foreldre som en del av temaet.

**Comment by oystein-asnes** [comment]
Tittel på issuel er endret til "Familie og barn" (var Barn og familie)

**Comment by stephanie-lovenskiold** [comment]
Jeg ser noe i denne: https://github.com/difi/los/blob/Los-versjon-2.1/source.xml som jeg ikke skjeønner. Ser ut som det ligger et tema parallelt med Familie og barn, som heter Foreldre og foresatte. Kan ikke gjenfinne det noe annet sted.
