### ISSUE TITLE
[ord] Opprette emneordene Gravferd og Gravplass

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#11]
Er relatert til #10 og #1

**Comment by oystein-asnes** [comment]
Gravferd eksisterer i v 2.0 . Har lagt til relasjon til "Barn og familie"

**Comment by stephanie-lovenskiold** [comment]
Åpnet denne igjen pga relasjonene til Religion og livssyn som ligger under Individ og samfunn og som skal vurderes. I tillegg er det en relasjon til dødsfall som kanskje hører til Los 2.0? Og som vel skal fjernes.
