### ISSUE TITLE
[ord] Vurdere fjerning av  emneord fra undertemaet "Arbeidsliv"

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#131]
Er relatert til: #104 
Beskrivelse:
Følgende emneord er ikke relevante for NAV og det må gjøres en vurdering av om de skal fjernes fra Los 3.0: 
- `Arbeidsavtale` 
- `Arbeidstid`
- `Arbeidstvist`
- `Innemiljø`   
- `Mobbing`

**Comment by Elianne** [comment]
Skal dette vente til vurdering er tatt? @oystein-asnes

**Comment by MartaKari** [comment]
Lågt blodsukker her, men kjem med eit forslag: @oystein-asnes
* Arbeidsavtale. Det finst standard arbeidsavtalar på nett. Frå Arbeidstilsynet, i Word.  Har vi med andre liknande avtalar i Los? 
* Arbeidstid er vel ikkje noko teneste, men regulert i lovverket. Eg føreslår at vi fjernar det emneordet
* Arbeidstvist. Teneste? Har vi framleis 'Fagforening' som emneord? Kan ev. liggja der?Viss det skulle vera det, kan dei 
* Innemiljø er emneord under Folkehelse. Ha det begge stader? 
* Mobbing. Viss vi vel å ikkje spesifisera i 'mobbing i arbeidslivet', 'mobbing i skulen'  +++, kan vi ha dette emne ordet og så knyta det til fleire tema

**Comment by oystein-asnes** [comment]
> Lågt blodsukker her, men kjem med eit forslag: @oystein-asnes
> 
> * Arbeidsavtale. Det finst standard arbeidsavtalar på nett. Frå Arbeidstilsynet, i Word.  Har vi med andre liknande avtalar i Los?

Ingen andre avtalar i Los 2.0. Slettes.
> * Arbeidstid er vel ikkje noko teneste, men regulert i lovverket. Eg føreslår at vi fjernar det emneordet

Enig. Fjernes.
> * Arbeidstvist. Teneste? Har vi framleis 'Fagforening' som emneord? Kan ev. liggja der?Viss det skulle vera det, kan dei

Fagforening er kun skjult emneord til arbeidstvist. Foreslår at `Arbeidstvist `fjernes.
> * Innemiljø er emneord under `Folkehelse`. Ha det begge stader?

Ligger nå  under `Skolemiljø `og `Folkehelse`. Beholdes under `Arbeidsliv`
> * Mobbing. Viss vi vel å ikkje spesifisera i 'mobbing i arbeidslivet', 'mobbing i skulen'  +++, kan vi ha dette emne ordet og så knyta det til fleire tema

`Mobbing` er fjernet som emneord. Er erstattet av `Mobbing i Skolen` og er dermed ikke relevant i denne konteksten. `Mobbing i arbeidslivet` vurderes når det kommer forslag om dette. KS har ikke foreslått dette.

**Comment by MartaKari** [comment]
Foreslår at `Arbeidsavtale `beholdes fordi det er en tjeneste som offentlig sektor leverer og det er aktuelt for mange, spesielt ungdommer.
