### ISSUE TITLE
[tema] Oppdatere undertemaet Hjelpemidler

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#144]
Er relatert til: #140.  Skal inneholde (liste fra KS): 

- [x] Bevegelseshjelpemidler
- [x] Hørselshjelpemidler
- [x] Kommunikasjon og kognisjon
- [x] Synshjelpemidler

Her kommer det mer fra NAV

**Comment by Elianne** [comment]
- [ ] Hjelpemiddel for bevegelse (_Bevegelseshjelpemidler_)
- [ ] Hjelpemiddel for syn (_Synshjelpemidler_)
- [ ] Hjelpemiddel for hørsel (_Hørselshjelpemidler_)
- [ ] Hjelpemiddel for tale og språk (_Kommunikasjon og kognisjon_)
- [ ] Hjelpemiddel for kognisjon (_Kommunikasjon og kognisjon_)
- [ ] Hjelpemiddel for lesing og skriving (_Kommunikasjon og kognisjon_)

Desse ligger inne i NAV sitt forslag, og er således allerede dekket av LOS.
