### ISSUE TITLE
[ord] Fjerne familievern ?

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#15]
Er relatert til #1 , #9 
Erstattes av *Barnevern og familiestøtte -> Støtte til familier*
 hidden labels fra *Familievern* er gjenbrukt.

**Comment by oystein-asnes** [comment]
Obs. Definisjonen er *Offentlege og kyrkjelege rettleiingstenester som gjev hjelp og råd i alle slags konfliktar og kriser i familieforhold. Kontora skal godkjennast av Barne- og likestillingsdepartementet*

- Sjekke om dette eksisterer som ikke-kommunal tjeneste før eventuelt sletting.

**Comment by oystein-asnes** [comment]
Lov om familievernkontor: https://lovdata.no/dokument/NL/lov/1997-06-19-62?q=familievernkontor

**Comment by oystein-asnes** [comment]
Emneordet  fjernes. For senere dokumentasjon så det slik ut:
   <Concept path="ord/familievern">
      <PrefLabel lang="en">Family counselling</PrefLabel>
      <PrefLabel lang="nb">Familievern</PrefLabel>
      <PrefLabel lang="nn">Familievern</PrefLabel>
      <HiddenLabel lang="nb">Husmorvikar</HiddenLabel>
      <HiddenLabel lang="nn">Husmorvikar</HiddenLabel>
      <HiddenLabel lang="nb">Familierådgiving</HiddenLabel>
      <HiddenLabel lang="nn">Familierådgjeving</HiddenLabel>
      <HiddenLabel lang="nb">Samlivskurs</HiddenLabel>
      <HiddenLabel lang="nn">Samlivskurs</HiddenLabel>
      <HiddenLabel lang="nb">Parkurs</HiddenLabel>
      <HiddenLabel lang="nn">Parkurs</HiddenLabel>
      <HiddenLabel lang="nb">Familierådgivning</HiddenLabel>
      <HiddenLabel lang="nn">Familierådgjeving</HiddenLabel>
      <HiddenLabel lang="nb">Familievernkontor</HiddenLabel>
      <HiddenLabel lang="nn">Familievernkontor</HiddenLabel>
      <HiddenLabel lang="nb">Familiekontor</HiddenLabel>
      <HiddenLabel lang="nn">Familiekontor</HiddenLabel>
      <Definition lang="nn">Offentlege og kyrkjelege rettleiingstenester som gjev hjelp og råd i alle slags konfliktar og kriser i familieforhold. Kontora skal godkjennast av Barne- og likestillingsdepartementet.</Definition>
      <InScheme>ontologi/ord</InScheme>
      <Broader>tema/barnevern-og-foreldrestotte</Broader>
      <Broader>tema/samliv</Broader>
   </Concept>

**Comment by stephanie-lovenskiold** [comment]
Sjekket og OK
