### ISSUE TITLE
[ord] Vurdere emneord under Familie og barn som ikke er del av KS sitt forslag

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#167]
Er relatert til: #1 
Beskrivelse: Vurdere om emneordene som KS ikke har i sin oversikt skal leve videre eller ikke.

**Comment by oystein-asnes** [comment]
Kryss av for emneord som skal **fjernes** fra Los. 
Barnehage:
- [ ] Barnepark
- [ ] Pedagogisk-psykologisk tjeneste

Barnevern og foreldrestøtte
- [ ] Besøkshjem
- [ ] Overgrep

Dødsfall og gravferd
- [ ] Dødsattest
- [ ] Dødsmelding
- [ ] Gravferdsstønad
- [ ] Skifte

Ekteskap
- [ ] Separasjon og skilsmisse

**Comment by stephanie-lovenskiold** [comment]
Jeg vil argumentere for at emneordet Pedagogisk-psykologisk tjeneste fjernes fra Barnehage-temaet. 
PPT er ikke noe man bare kan søke om. Det er en ressurs for de som driver barnehager og skoler. Uansett, tjenester som PPT og spesialpedagogisk hjelp (som er nytt siden Los 2.0) kan gå inn under emneordet Barnehage - innhold og kvalitet.

**Comment by stephanie-lovenskiold** [comment]
Ordet overgrep - kunne vi kalt det for "Tjenester for Overgrepsutsatte"?

Jeg vil gjerne også melde inn forslag om at vi endrer ordene Mobbing til "Tiltak mot mobbing" og Livskriser til "Hjelp ved livskriser"

**Comment by MartaKari** [comment]
`Pedagogisk-psykologisk tjeneste` ligger allerede under `Grunnskole` og `Fag- og yrkesopplæring`. Det bør også inn under `Videregående skole`. Foreldre kan sammen med kommunen søke om henvisning. I og med at Pedagogisk-psykologisk tjeneste er emneord, er det er fordel at det hete det samme dersom det skal være med under Barnehage-temaet.

**Comment by oystein-asnes** [comment]
`Overgrep` endres til `Hjelp ved overgrep`
