### ISSUE TITLE
Script el.l. for å eksportere hele los-strukturen til en flernivå csv-fil

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#169]
Det er behov for en eksport til CSV  eller tilsvarende slik at det er mulig å se hele Los-strukturen som et flernivå regneark i f.eks Excel

>En annen ting @oystein-asnes og @klakegg - har dere en kjapp og grei oppskrift / script el.l. for å eksportere hele los-strukturen til en flernivå csv-fil?

>_Originally posted by @jmfurseth in https://github.com/difi/los/issues/138#issuecomment-539414495_

**Comment by jmfurseth** [comment]
Har tenkt på noen mulige inretninger her - det finnes sikkert også flere lure triks (inkl smarte rdf-verktøy og andre jeg ikke kjenner):
- lage et script som traverserer rdf eller html "fra toppen" (?) og parser og bygger opp en matrisestruktur som så kan eksporteres til csv
- generere hele los datasettet som en csv ved publisering

HTML-visningen kan forsåvidt også tilrettelegges slik at import i Excel / Sheets går - blir riktignok da bare en og en fil, så det gir en litt begrenset løsning.

**Comment by klakegg** [comment]
Jeg laget en visning.

Bokmål: http://psi.norge.no/los/3/view/table-nb
Nynorsk: http://psi.norge.no/los/3/view/table-nn
Engelsk: http://psi.norge.no/los/3/view/table-en

**Comment by jmfurseth** [comment]
Jepp, dette er strålende :-) Liten knirk på denne: Excel gidder ikke importere herfra, rapporterer at HTML output er i Explorer kompatibilitets-modus som ikke høres så oppløftende ut :-P Så denne i høringsnotatet og tenkte - har denne vært her hele tiden, men ser nå at dette er nybrottsarbeide! Tenkte også Json hadde blitt nifty her, men - etter hvert. Du er absolutt inne på en veldig bra tilnærming her, @klakegg  !
