### ISSUE TITLE
[ord] Opprette Tvangsekteskap

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#17]
Er relatert til #1 og #7

**Comment by oystein-asnes** [comment]
Emneordet eksisterer i Los 2.0 under tema/barnevern-og-familievern. Relasjon og definisjon må oppdateres.

**Comment by oystein-asnes** [comment]
Flyttes til tema/ekteskap

**Comment by stephanie-lovenskiold** [comment]
Sjekket og OK
