### ISSUE TITLE
[ord] Vurdere behov for Ytelser til arbeidssøker

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#170]
Er relatert til: #104 
Beskrivelse: I et arbeidsmøte er `Ytelser til arbeidssøker`  nevnt som en kandidat (jf [Ytelser til foreldre og foresatte](http://psi.norge.no/los/3/ord/ytelser-til-foreldre-og-foresatte.html). Vurdere behov og se på overlapp med eksisterende og mer spesifikke emneord.

**Comment by MartaKari** [comment]
`Ytelser til arbeidssøker` ser ut til å overlappe med temaet `Inntektssikring`. Bør i tilfelle velge ett av dem.
