### ISSUE TITLE
[tema] Opprette Arbeidssøking som eget undertema

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#173]
Er relatert til: #104 
`Arbeidssøking `endres fra å være emneord til et eget undertema under `Arbeid`. Skal inneholde:

- [x] Arbeidsmarkedstiltak 
- [x] Arbeidstillatelse 
- [x] CV (?)
- [x] Yrkesautorisasjon

**Comment by MartaKari** [comment]
Under temaet `Arbeidssøking `mangler et emneord om å søke arbeid, f.eks.  `Søke jobb` eller `Søke arbeid`
