### ISSUE TITLE
[tema] Opprette hovedkategorien Bolig og sosiale tjenester

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#18]
Navnet overlapper delvis med Los 2.0 hovedkategori *Bolig og eiendom* som inneholder følgende underkategorier: *bygging, eiendom, flytting, kjøp og salg, kommunal planlegging, leie og utleie, tekniske tjenester*

*Bolig og sosiale tjenester* inneholder følgende underkategorier: *Botilbud, Kvalifisering til arbeid, Økonomisk støtte og rådgivning*

**Comment by oystein-asnes** [comment]
Forslag til løsning: Nedre navn til *Sosiale tjenester og botilbud*

**Comment by marittor** [comment]
Endringer etter møte: Har konkludert med å ta bort "Bolig" fra navnet til hovedkategorien, da står vi igjen med hovedkategorien "sosiale tjenester". Denne hovedkategorien må sees i lys av "Omsorg, trygd og sosiale tjenester". Kan vurdere merge her?
