### ISSUE TITLE
[ord] Lage ny definisjon til Tolketjenester

### ISSUE THREAD

**Issue by Elianne** [difi/los#193]
Er relatert til: #45

Beskrivelse:

**Comment by MartaKari** [comment]
#193
Forslag 1:
En tolketjeneste er en tjeneste som mest mulig trofast overfører budskapet mellom mennesker som mangler et felles språk. Budskapet kan være gjengitt på tegnspråk eller muntlig på et annet språk. 

Forslag 2:
En tolketjeneste er en tjeneste som gjengir muntlig eller på tegnspråk, og på annet språk, en persons tale for andre lyttere på det tidspunktet ytringen blir gjort.

**Comment by Elianne** [comment]
Er denne klar? @oystein-asnes @stephanie-lovenskiold

**Comment by oystein-asnes** [comment]
Tjenester som gjengir en persons tale for andre lyttere på det tidspunktet ytringen blir gjort. Gjengivelsen kan være muntlig, skriftlig eller på tegnspråk, og (oftest) på annet språk.
