### ISSUE TITLE
[ord] Slå saman emneorda Trygghet i hjemmet og Trygghetsalarm

### ISSUE THREAD

**Issue by MartaKari** [difi/los#197]
Er relatert til: #140 

Beskrivelse: Føreslår at emneordet blir `Trygghet i hjemmet`. `Trygghetsalarm` som skjult emneord.

**Comment by oystein-asnes** [comment]
Merk at Trygghetsalarm både kan være fastmontert alarm (i hjemmet) og mobil trygghetsalarm.

>  [...] alarmen gir de eldre større frihet og mulighet for et mer aktivt liv utenfor hjemmet.

https://forskning.no/aldring-helsetjenester-sikkerhet/mobil-trygghetsalarm-slar-an-hos-eldre/474375

I Elverum kommune kan eksempelvis brukerne velge selv: https://www.elverum.kommune.no/helse-og-omsorg/hjemmebaserte-tjenester/trygghetsalarm

**Comment by oystein-asnes** [comment]
Beskrivelsen/definisjonen på "Trygghet i hjemmet" er slik:

> Omfatter kommunale tjenester og tekniske løsninger som gir hjemmeboende syke og eldre mer selvstendighet, medbestemmelse, livskvalitet og komfort.

Hvilke tjenester og tekniske løsninger er det snakk om? Disse bør inn som skjulte søkeord. Jeg ser eksempelvis at NAV fortsatt har støtte til Komfyrvakt: https://www.ksbedrift.no/aktuelt/brann-og-redning/komfyrvakt-faar-nav-stoette/ (og dette er en statlig tjeneste)

**Forslag til løsning:** 

1. Berike `Trygghet i hjemmet` med relevante tjenester og tekniske løsninger inkludert `Trygghetsalarm` og `Komfyrvakt`
2. Endre emneordet `Trygghetsalarm` til` Mobil trygghetsalarm` og relatere det til `Trygghet i hjemmet`
3. Slette "kommmunale" fra beskrivelsen ettersom staten også leverer tjenester her.

Kommentarer her @MartaKari , @klakegg @stephanie-lovenskiold @jmfurseth ?

**Comment by stephanie-lovenskiold** [comment]
Her er forslag til skjulte søkeord:

elektronisk medisindispenser
sensorer for egenmåling
medisinsk oppfølging
elektroniske dørlås 
e-lås
døralarm
digital varsling
trygghetsalarm
responstjenester
lokaliseringstjeneste (GPS)
robotstøvsuger
talehjelpemiddel
digital kalender
fall-, bevegelse- og røykvarsling
matlevering
rengjøringshjelp

**Comment by MartaKari** [comment]
Føreslår `Trygghetsalarm `i staden for `Mobil trygghetsalarm` sidan Trygghetsalarm kan omfatta alle typar tryggheitsalarmar.

**Comment by MartaKari** [comment]
Føreslår `Trygghetsalarm `i staden for `Mobil trygghetsalarm` sidan `Trygghetsalarm` kan omfatta alle typar tryggheitsalarmar.
@klakegg @stephanie-lovenskiold @jmfurseth

**Comment by MartaKari** [comment]
Fin liste med skjulte søkeord. For at søkemotorane skal finna orda, er det lurt å skriva dei full ut: fallvarsling, bevegelsesvarsling og røykvarsling.

**Comment by oystein-asnes** [comment]
`Matlevering `legges ikke til som skjulte søkeord for det er et egen emneord. Legges til som relatert. 
`Rengjøringshjelp `legge til som skjult søkeord til `Hjemmehjelp`.
Øvrige emneordene leggs til i listen over til som foreslått.

**Comment by jmfurseth** [comment]
Trygghet er bra, om det så er i hjemmet eller mobilt eller om brukeren er eldre, funksjonshemmet eller rett og slett bare trenger `Trygghetstjenester` (?) eller `Hjelpemidler `:-P Men, litt vanskelig også å samtidig "fange" de spesifikke kontekstene som tjenesten(e) og hjelpemidlene kan inngå i som emneord... Trenger vi egentlig det?
