### ISSUE TITLE
[tema] Trafikkinformasjon ligger både som tema og som emneord

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#198]
Er relatert til: #77 

**Beskrivelse** 
Trafikkinformasjon er nå både et tema og et emneord jf http://psi.norge.no/los/3/tema/trafikkinformasjon.html og http://psi.norge.no/los/3/ord/trafikkinformasjon.html

Jeg samtidig litt usikker på `Miljøvennlig transport` og `Trafikksikkerhet` som emneord knyttet til `Trafikkinformasjon`. 

**Løsningsforslag**: Endre emneordet `Trafikkinformasjon` til `Trafikkmeldinger` ?

**Comment by hildea** [comment]
Vi ser en av to løsninger:

1. Døpe om nivå-3-forekomsten av «Trafikkinformasjon» til «Statisk trafikkinformasjon»
2. Droppe nivå-3-forekomsten av «Trafikkinformasjon» i denne omgangen, så kan vi tenke på en varig løsning til neste versjon

Vi skal tygge litt mer på det for å finne ut hvilken av dem vi går for.

**Comment by MartaKari** [comment]
Emneordet `Trafikkinformasjon` har disse skjulte emneordene: `Kolonnekjøring`, `Omkjøring`, `Vegmelding`, `Vegstenging`. `Trafikkmelding `dekker alt dette. Foreslår å endre emneordet til `Trafikkmelding` og la temanavnet bestå.

**Comment by hildea** [comment]
Trafikkmelding er ikke dekkende for alt vi ønsker å legge inn her. 

Vi har en ny nivå 3-term: Sanntids trafikkinformasjon. Vi går for å døpe om "Trafikkinformasjon" til "Sanntids trafikkinformasjon". Og så beholder vi de skjulte emneordene.

**Comment by oystein-asnes** [comment]
Jeg ser at en rekke av forslagene fra SVV handler om oppdateringsfrekvens (sanntid, dynamiske; statiske). Jeg tror ikke dette er en dimensjon som Los skal løse, men som må adresseres i DCAT. Her er det allerede etablert et vokabular for oppdateringsfrekvens knyttt til  denne egenskapen https://doc.difi.no/dcat-ap-no/#datasett-frekvens. Dersom dette ikke dekker behovet må dette meldes inn i forbindelse med [DCAT-revisjonen](https://github.com/difi/dcat-ap-no/issues). 

Eksempler på andre emneord i oversendt forslag er:
- Dynamiske trafikksignaler og reguleringer 
- Dynamisk veg og føreforhold 
- Statiske trafikksignaler og reguleringer
