### ISSUE TITLE
[ord] Legge til: Barnehage - innhold og kvalitet 

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#2]
Relatert til #1

**Comment by klakegg** [comment]
Navnet er ikke helt bra, det er sikkert flere ting som kan knyttes til "kvalitet" enn barnehage, og det er ikke helt klar for meg hvilket (kommunalt) innhold som skal kobles til dette.

**Comment by oystein-asnes** [comment]
Finne et bedre begrep

**Comment by oystein-asnes** [comment]
Emneordet er opprettet og saken lukkes
