### ISSUE TITLE
[tema] Innvandring og integrering er ikke vurdert

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#204]
Er relatert til:

**Beskrivelse**: Hovudtemaet `Innvandring og integrering` er ikke vurdert. Inneholder i dag:
[`Innvandring og innreise`](http://psi.norge.no/los/tema/innvandring-og-innreise)
[`Integrering`](http://psi.norge.no/los/tema/integrering)

**Løsningsforslag**

**Comment by oystein-asnes** [comment]
Vi beholder `Innvandring og integrering` som navn på hovudtema. @stephanie-lovenskiold foreslår nye tema og emneord. @MartaKari vurderer om resterende innhold skal leve videre.

**Comment by stephanie-lovenskiold** [comment]
Forslag til emneord til temaet **Integrering**

- Asylmottak
- Botilbud for innvandrere
- Fritidstilbud for fremmedspråklige
- Helsetjenester for fremmedspråklige
- Opplæringstilbud for fremmedspråklige
- Tolk

**Comment by stephanie-lovenskiold** [comment]
Jeg har sett på nettsidene til noen store kommuner og noen mindre kommuner og kommet fram til disse emneordene som jeg mener dekker det tilbudet kommunen og fylkeskommunen gir. En som tidligere jobbet i NAV foreslo at jeg kunne bruke termen fremmedspråklige istdf "flyktninger, asylsøkere og innvandrere".
Kom gjerne med synspunkter dere andre.
Når vi er enige legger jeg inn nynorsk, engelsk og definisjoner.

**Comment by MartaKari** [comment]
Eg meiner vi bør bruka termane flyktningar, asylsøkarar og innvandrarar. `Fremmedspråklig` er ein vidare term, og vi får då ikkje skilt mellom flyktningar og t.d. ein arbeidsinnvandrar frå USA.

**Comment by MartaKari** [comment]
Emneoerd til temaet `Interering`, kommentarar:

- Asylmottak (Flytte til temaet `Innvandring og innreise`. `Transittmottak `som hjelpeord)
- Botilbud for innvandrere (Vi har emneordet 'Kommunal bolig'. Bruke det?)
- Fritidstilbud for fremmedspråklige (Fjerne og heller koble emneordet `Fritidstilbud `til Integrering )
- Helsetjenester for fremmedspråklige (Har kommunene eigne tenester? I tilfelle heller skrive `Helsetjenester for innvandrere` eller `Helsetjeneste for flyktninger og asylsøkere`)
- Opplæringstilbud for fremmedspråklige (Erstatte med `Introduksjonsprogram for innvandrere` )
- Tolk (Bruke som hjelpeord til `Tolketjeneste `)

Ev kople til desse emneorda: 
- `Språkkurs og språktest` 
-  `Særskilt norskopplæring`
@stephanie-lovenskiold

**Comment by MartaKari** [comment]
Undertemaet `Innvandring og innreise` har desse emneorda:

- Arbeidstillatelse
- Flyktninger og beskyttelse (ev. `Asylmottak`)
- Oppholdstillatelse
- Pass
- Statsborgerskap
- Visum

@stephanie-lovenskiold

**Comment by stephanie-lovenskiold** [comment]
> Eg meiner vi bør bruka termane flyktningar, asylsøkarar og innvandrarar. Fremmedspråklig er ein vidare term, og vi får då ikkje skilt mellom flyktningar og t.d. ein arbeidsinnvandrar frå USA.

Ja, jeg kjøper den. Likte ikke fremmedspråklig så godt selv.

**Comment by stephanie-lovenskiold** [comment]
> Emneoerd til temaet Interering, kommentarar:
> 

> > Asylmottak (Flytte til temaet Innvandring og innreise. Transittmottak som hjelpeord) 
OK

> > Botilbud for innvandrere (Vi har emneordet 'Kommunal bolig'. Bruke det?)

Nei. det er flere ordninger for bosetting, ikke bare kommunal bolig.

> > Fritidstilbud for fremmedspråklige (Fjerne og heller koble emneordet Fritidstilbud til Integrering ) 
OK
> > Helsetjenester for fremmedspråklige (Har kommunene eigne tenester? I tilfelle heller skrive Helsetjenester for innvandrere eller Helsetjeneste for flyktninger og asylsøkere)


Da må det i så fall bli `Helsetjenester for flyktninger og asylsøkere.` Det at innvandrere, de med opphold har rett på helsetjenester er vel naturlig. Men her referer jeg til tjenester spesielt for de som enda ikke har opphold.

> > Opplæringstilbud for fremmedspråklige (Erstatte med Introduksjonsprogram for innvandrere )
Nei. Det finnes flere lovpålagte opplæringstilbud, blant annet til de som bor i asylmottak. Og flere kan det bli. Denne dekker alt, også tjenester som skolen er ansvarlig for.

> > Tolk (Bruke som hjelpeord til Tolketjeneste )


Ja
> Ev kople til desse emneorda:
> 
> Språkkurs og språktest
> Særskilt norskopplæring
> @stephanie-lovenskiold

Jeg mente å fjerne de to, og heller bruke Opplæringstilbud som skal dekke disse og flere til.

**Comment by stephanie-lovenskiold** [comment]
Så da blir det slik @MartaKari?
Asylmottak eget emneord under Innvandring og innreise

**Integrering**
- Botilbud for innvandrere
- Fritidstilbud - tilpasse definisjonen sånn at den dekker begge
- Helsetjenester for flyktninger og asylsøkere
- Opplæringstilbud for fremmedspråklige/Opplæringstilbud for flyktninger, asylsøkere og innvandrere
- Tolketjeneste

**Comment by MartaKari** [comment]
Ja, einig slik strukturen no er @stephanie-lovenskiold 

Vi kan bruke `Introduksjonsprogram for innvandrere` som hjelpeord til 'Opplæringstilbud .....' 

Ev. også relatere til `Språkkurs og språktest`
