### ISSUE TITLE
[tema] Bygg og eiendom

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#205]
Er relatert til:

**Beskrivelse** 
tror at psi-en ikke er oppdatert for Bygg og eiendom
**Løsningsforslag**
I følge mine notater og Trello skal temaet Bygg og eiendom se slik ut, se under:

**Kommunale planer** (Kommunalt)

- [x] (Kommentar: Bebyggelsesplan - ta med som emneord?)
- [x] Kommunedelplan
- [x] Kommuneplan
- [x] Private reguleringsplaner (Kommentar: kan dette gå inn under Reguleringsplan?))
- [x] Reguleringsplan
- [x] Temaplan
- [x] Regionale planer
 Fylkesplan
 Fylkesdelplan
(Kommentar: Samfunnsplan - ta med som emneord) 

**Bygging**  (kommunalt)

- [x] Byggesak
- [x] Forhåndskonferanse
- [x] Forurenset grunn
- [x] Klage på byggesak
- [x] Nabovarsel
- [x] Melding om ulovlige tiltak
- [x] Melding til kommunen (Kommentar: Kan oppfattes som generell melding til kommunen. Er det "Melding om bygning eller tilbygg som er unntatt søknadsplikt" det er snakk om, bør emneordet endres, f.eks. "Bygge uten å søke eller "Bygge uten byggesøknad" ) **Melding om bygging**

**Eiendom** (kommunalt)

- [x] Adressetildeling
Avfall
- [x] Bolignummer
- [x] Deling av eiendom 
- [x] Eiendomsregister
- [x] Feiing
- [x] Fredet eiendom
- [x] Heftelser på eiendom
- [x] Kommunale avgifter og gebyrer
- [x] Konsesjon/boplikt
- [x] Oppmåling
- [x] Privat avkjørsel/vei
- [x] Seksjonering
- [x] Vann og avløp

Priser og gebyrer for bygging og eiendom** (kommunalt)
- [x] Betalingssatser
- [x] Eiendomsskatt
- [x] Gebyrer for byggesak /   gebyrregulativ
- [x] Renovasjonsavgift

**Flytting** (statlig)
- [x] Bostedsattest
- [x] Flyttemelding

Kjøp og salg** (statlig)
- [x] Boligfinansiering
- [x] Eiendomsomsetning
- [x] Tinglysing

*Leie og utleie*
- [x] Kommunal bolig
- [x] Leieforhold
- [x] Tomtefeste

**Comment by Elianne** [comment]
Jeg skal få rettet opp.

**Comment by oystein-asnes** [comment]
`Samfunnsplan `legges til som skjult søkeord til `Kommuneplan`. @Elianne oppdaterer

**Comment by oystein-asnes** [comment]
> Privat avkjørsel/vei . 

Sjekk referanse/overlapp med `Trafikk og transport`

> Avfall 

Denne overlapper med `Renovasjon `under `Avfallshåndtering`.  Denne skilles ut som egen oppgave.

**Comment by oystein-asnes** [comment]
`Tekniske tjenester` skal fjernes fra Los fordi alle som ligger under temaet ligger andre steder. 
`Avløpshåndtering` og `Vannforsyning `fjernes
