### ISSUE TITLE
[tema] Oppdatere Næringsutvikling

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#216]
Er relatert til: #95 
Næringsutvikling = Aktiviteter som det offentlige gjør for å tiltrekke seg aktivitet i sin geografi/domene/mm

**Comment by stephanie-lovenskiold** [comment]
Forslag til tema næringsutvikling:
**Næringsutvikling**
- Næringsareal
- Næringsklynger
- Støtte til bedrifter

**Comment by Elianne** [comment]
Kva med desse:
```
Bransjekrav
Foretaksregistrering - erstatta av Støtte til bedrifter?
Konkurs
Oppgåveplikt

```

**Comment by Elianne** [comment]
Samme som med næringsliv - eg har haka av dei som Stephanie har sagt skal ligga under Næringsutvilking. Dei so ikkje er haka av er ikkje vurdert, men ligg no under Næringsutvikling. @stephanie-lovenskiold vurderer fyrst om desse skal med, slettast eller flyttast, deretter ser @MartaKari på det i runde to.

**Comment by stephanie-lovenskiold** [comment]
Jeg foreslår å fjerne de som ikke har hake. De er ivaretatt under Næringsliv eller Skatt og avgift.

**Comment by stephanie-lovenskiold** [comment]
- [ ] 2. `Oppgaveplikt` - har noe med skatt å gjøre
- [ ]  4. `Standardisering` - Er emneord under Næringsliv
- [ ]  6. `Bransjekrav` - er blitt til `Tjenester og krav til enkeltbransjer` under Næringsliv
- [ ]  7. `Foretaksregistrering` - er vel dekket under `Starte eller avslutte bedrift` under Næringsliv. Hvis ikke det heller handler om rapportering. Er ikke sikker.
- [ ]  8. `Konkurs` - blir til `Starte eller avslutte bedrift` under Næringsliv

**Comment by Elianne** [comment]
> * [ ]   4. `Standardisering` - Er emneord under Næringsliv
> *

`Standarder `er altså det samme som `Standardisering`? For ordet under Næringsliv er `Standarder`.
