### ISSUE TITLE
[tema] Oppdatere Næringsliv

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#217]
Er relatert til: 
 
 "Alt" som ikke inngår i Næringsutvikling

**Comment by stephanie-lovenskiold** [comment]
Forslag til tema **Næringsliv**:

- Bevillinger og tillatelser
- Patent, design og varemerke
- Rapportering
- Sertifisering og autorisasjon
- Standarder
- Starte eller avslutte bedrift
- Tjenester og krav til arbeidsgiver
- Tjenester og krav til enkeltbransjer
- Tilsyn og kontroll med næringsvirksomhet
- Utenlandsk bedrift
-

**Comment by Elianne** [comment]
- [ ] Bransjekrav
- [ ] Designbeskyttelse, Varemerke, Patent - blir til Patent, design og varemerke
- [ ] Foretaksregistrering
- [ ] Konkurs
- [ ] Næringsareal (ligg også under reguleringsplan)
- [ ] Oppgaveplikt

- [ ] Standardisering

**Comment by Elianne** [comment]
Nå har eg haka av dei som Stephanie la inn som nye, og dei som ikkje er haka av må vurderast: skal dei vera der dei er, skal dei flyttast eller skal dei vekk? @stephanie-lovenskiold  vurderer fyrst, og deretter @MartaKari.

**Comment by stephanie-lovenskiold** [comment]
Mitt forslag er å fjerne alle de som ikke er haket av. Alle skal være dekket av de nye emneordene.

**Comment by stephanie-lovenskiold** [comment]
Jeg var litt rask. Jeg forutsetter nå at Skatt og avgift er et eget tema. Det er det ikke sant?

**Comment by Elianne** [comment]
> Jeg var litt rask. Jeg forutsetter nå at Skatt og avgift er et eget tema. Det er det ikke sant?

Skatt og avgift er eige tema ja. Men kunne du da ha haka av dei som er dekka av dei orda som er nye, slik at eg kan gå over dei orda som gjenstår, og sjå at dei er knytt til andre tema?

**Comment by stephanie-lovenskiold** [comment]
- [ ]  1. `Arbeidsgiveravgift` - dekkes under Skatt og avgift
- [ ]  12. `Bedriftsetablering` - blir til Starte eller avslutte bedrift
- [ ]  13. `Etablere barnehage` - dekkes av Starte eller avslutte bedrift. Kan legges inn som skjult søkeord.
- [ ]  14. `Formue- og innteksskatt` - dekkes av Betaling av skatt under Skatt og avgift
- [ ]  15. `Miljøsertifisering` - dekkes av Sertifisering og autorisasjon. kan legges inn som skjult søkeord.
- [ ] 16. `Næringsfond` - dekkes av Støtte til bedrifter under Næringsutvikling. Kan brukes som skjult søkeord.
- [ ]  17. `Tilsyn med næringsliv` - blir til Tilsyn og kontroll med næringsvirksomhet
- [ ]  18. `Skatteattest` - flyttes til Skatt og avgift.

**Comment by MartaKari** [comment]
Kommentarar til # 217 `Næringsliv`

I 3.0 ligg framleis undertemaet Handel og service, med bl.a. emneorda `Torgsalg`, `Produktsikkerhet`. Kunne ha vore med, ev. som hjelpeord.
