### ISSUE TITLE
[ord] Vurdere avfall som emneord

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#218]
Er relatert til: 

Beskrivelse:

**Comment by Elianne** [comment]
Forslag: Legge inn avfall som skjult emneord under renovasjon. Under emneord Renovasjon ligg det avfallsbeholder og avfallsplan inne som skjult emneord, og ordet avfall dekka ganske grundig i sjølve definisjonen. @oystein-asnes

**Comment by oystein-asnes** [comment]
Legges som hjelpeord  (aka skjult søkeord) til `Renovasjon`
