### ISSUE TITLE
[tema] Slå sammen Pensjon og Inntektssikring

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#219]
Er relatert til: 

**Beskrivelse** 

- [x] `Pensjon` demonteres og emneordene legges inn under `Inntektsikring`
- [x] `Barnepensjon `relateres også til `Familieytelser`
- [x] `Ektefellepensjon `relateres også til `Familieytelser`

**Løsningsforslag**

**Comment by oystein-asnes** [comment]
@jmfurseth Vurderer om det er mulig å slå sammen til "Pensjon og Inntektssikring"

**Comment by oystein-asnes** [comment]
Obs: Vi har et konkurrerende forslag over hos #228 som ser slik ut:

> Vi bruker alternativ term (Skos:AltLabel) aktivt for å sikre at det er samsvar mellom temanavn og innhold i "Kommune-Los". Vi kan da anbefale kommunene å bruke alternativ term eksplisitt.

> Vi endrer navn på Sosiale tjenester til Pensjon, trygd og sosiale-tjenester og legger til Sosiale tjenester som alternativ term (=anbefalt for kommunene).

> Vi legger til Pensjon som "nytt" (vi har nettopp fjernet det) undertema til Pensjon, trygd og sosiale-tjenester og relaterer alle pensjonsytelsene her. Temaet relateres i praksis til innhold som eksisterer andre steder i Los (feks under undertemaet Inntektssikring), men samler alle pensjoner i samme bøtte.

**Comment by jmfurseth** [comment]
Vi får ta en prat om denne @randiaasen - kanskje du skulle stått som "Assignee" heller enn meg?

**Comment by oystein-asnes** [comment]
Dekket av #228 ? Foreslår å lukke denne

**Comment by oystein-asnes** [comment]
Vi går for #228 . Denne avslås og lukkes.
