### ISSUE TITLE
[ord] Fylkesplan og Fylkesdelplan manglar definisjonar

### ISSUE THREAD

**Issue by Elianne** [difi/los#223]
Tema: Eiendom:
 Emneord: Fylkesplan og fylkesdelplan mangler nynorsk- og engelskterm, og definisjonar på begge målformer. @stephanie-lovenskiold

**Comment by stephanie-lovenskiold** [comment]
Fylkesdelplan (alternativt navn: Regional delplan)
Fylkesdelplan (alternativt navn: Regional delplan)
Regional sub-plan
En fylkesdelplan omfatter en bestemt del av fylkets totale areal.
Ein fylkesdelplan omfattar ein bestemt del av fylket sitt areal.

Fylkesplan (alternativt navn: Regional plan)
Fylkesplan (alternativt navn: Regional plan)
Regional master plan
Fylkesplanen er styrende for all planlegging i fylkeskommunen. Planen skal skape langsiktighet og forutsigbarhet i politikk og arealbruk for fylkets innbyggere. En effektiv planlegging forutsetter kontakt og samspill mellom fylkeskommunen, private lokale interesser og statlige og kommunale organer under utarbeidingen av planene. Gjennom åpne møter, informasjon og høring søker fylkeskommunen å stimulere til debatt og medvirkning før vedtak fattes.

Fylkesplanen er styrande for all planlegging i fylkeskommunen. Planen skal skape langsiktigheit og forutsigbarheit i politikk og arealbruk for fylket sine innbyggjarar. Ei effektiv planlegging føreset kontakt og samspel mellom fylkeskommunen, private lokale interesser og statlege og kommunale organ under utarbeidinga av planane. Gjennom opne møter, informasjon og høyring søkjer fylkeskommunen å stimulere til debatt og medverknad før avgjerd fattast.
