### ISSUE TITLE
[ord] Standarder som emneord til tema Næringsliv

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#237]
Er relatert til: 
#217 
Beskrivelse:
bm: Standarder
nn: Standard
en: Standards
def bm: En standard er en felles definisjon og beskrivelse på hvordan noe skal lages eller gjøres. Standarder gir detaljerte beskrivelser til EU-direktiver, lover og forskrifter og finnes for de fleste bransjer.
def nn: Eit standard er ein felles definisjon og omtale på korleis noko skal lagast eller gjerast. Standard gir detaljerte omtalar til EU-direktiv, lover og forskrifter og finst for dei fleste bransjar.

**Comment by oystein-asnes** [comment]
Standarder er sentralt også i offentlig sektor, m.a har vi  "Referansekatalogen for IT-standarder" som er en oversikt over IT-standarder som er obligatoriske eller anbefalte for offentlig sektor.  Dette henger sammen med behovet for et eget tema `Offentlig forvaltning` (eller et bedre ord) . 

Å spesifisere til "Standarder for næringslivet" tror jeg ikke er en god idé ettersom næringslivet gjerne er leverandører til offentlig sektor og at standardene vi gjelde i begge sektorer.

Foreslår vi kører denne gjennom som foreslått for `Næringsliv`, og ser nærmere på dette i forbindelse med et ev. tema `Offentlig forvaltning`.

**Comment by Elianne** [comment]
Vi har et emneord Standardisering under næringsutvikling i dag. Skal dette erstattes av Standarder? Definisjon: Omtale av viktige sider av varer, tenester og/eller arbeidsprosessar (inkludert prøvingsmetodar). Vert utarbeidd etter initiativ frå interessegrupper som ønskjer felles spelereglar i marknaden. Frivillig å bruke, unnateke når myndigheitene krev at dei skal brukast, eller når det i avtalar er bestemt at dei skal brukast. @stephanie-lovenskiold @oystein-asnes
