### ISSUE TITLE
[tema] Vurdere å demontere Innvandring og integrering

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#250]
Er relatert til:
#204 
**Beskrivelse** 
Skal Innvandring og integrering være et hovedtema?
Det kan se ut som om vi har få tjenester spesielt for innvandrere, asylsøkere osv. Samtidig har vi behov for temaet Innvandring og innreise fordi der ligger emneord som statsborgerskap, pass, visum osv.

Kommunale tjenester spesielt rettet mot denne gruppen er:

1. Opplæring i norsk og samfunnskunnskap (omfatter flere enn de som får delta i introduksjonsprogrammet)
2. Introduksjonsprogrammet
3. Opplæring i norsk og norsk kultur for de som bor i asylmottak

Samtidig brukes mange av de andre kommunale tjenestene til denne gruppen. eks barnevern, økonomiske ordninger, bosetting, helse, skole, tolk, barnehage.
Som vi snakket om, er helsetjenester for gruppen ivaretatt under Helsetjenester.
Det samme gjelder egentlig bolig, som er ivaretatt under Botilbud.
Fritidstilbud finnes også fra før. 
I KS' forslag til Los er introduksjonsprogram plassert under Kvalifisering til arbeid +  Voksenopplæring. De to andre kommunale tjenestene har ingen god plassering. 

**Løsningsforslag**
Jeg foreslår å demontere temaet.

**Integrering**

- [x] `Inkludering` - fjernes
- [x] `Introduksjonsprogram for   innvandrere` - er plassert to andre steder
- [x] `Norskopplæring` - er plassert under Voksen opplæring og kan omfatte de to opplæringstjenestene som ikke har fått egne emneord.
- [x] `Språkkurs og språktest` - fjernes. Ordninger for arbeidsinnvandrere, hvis det finnes, kommer inn under Norskopplæring
- [x] `Tolketjeneste` - er plassert under Medvirkning og Avlastning og støtte.
- [ ] 

**Innvandring og innreise**

- [x] `Arbeidstillatelse` - er plassert under arbeidsliv
- [x] `Flyktninger og beskyttelse` - trenger et tema. Forslag: Innbyggerrettigheter
- [x] `Oppholdstillatelse` - trenger et tema. Forslag: Innbyggerrettigheter
- [x] `Asylmottak` - hvis vi skal ha det, trenger et tema
- [x] `Pass` - er plassert under Innbyggerrettigheter
- [x] `Statsborgerskap` - er plassert under Innbyggerrettigheter
- [x] `Visum` - trenger et tema. Forslag: Setter den sammen med Pass som blir Pass og visum.

Hva synes dere?

**Comment by Elianne** [comment]
Jeg er enig, @stephanie-lovenskiold, Men, pass er ikke  eget tema, men emneord. Det ligger under `Innbyggerrettigheter `og `Innvandring og reise`.. 
Nytt forslag er å opprette VIsum som eget emneord, og knytte til samme tema som Pass.

**Comment by Elianne** [comment]
Fjerner asylmottak.

**Comment by MartaKari** [comment]
Støtter løysingsforslaget @stephanie-lovenskiold 

`Pass og visum` kan slåast saman til eitt emneord. 
`Asylmottak` kan bli hjelpeord under `Flyktininger og beskyttelse`
