### ISSUE TITLE
Standard

### ISSUE THREAD

**Issue by MartaKari** [difi/los#251]
Er relatert til: #217 Næringsliv

Definisjonen bør justerast. Opphavleg:   Informasjon, veiledning og hjelpemidler  for å imøtekomme krav for utenlandske bedrifter som skal drive næringsvirksomhet i Norge.

Standardar er ikkje berre for utanlandske bedrifter.

**Comment by Elianne** [comment]
Dette er gamle definisjonen av standard(isering): Omtale av viktige sider av varer, tenester og/eller arbeidsprosessar (inkludert prøvingsmetodar). Vert utarbeidd etter initiativ frå interessegrupper som ønskjer felles spelereglar i marknaden. Frivillig å bruke, unnateke når myndigheitene krev at dei skal brukast, eller når det i avtalar er bestemt at dei skal brukast.
