### ISSUE TITLE
[tema] Sjekke at alle tema er vurdert

### ISSUE THREAD

**Issue by Elianne** [difi/los#256]
Er relatert til:

**Beskrivelse** 
Det viser seg at det er behov for å sjekke om alle tema er behandlet. Jeg sjekker at alle tema dukker opp i Github. De som ikke gjør det, blir notert ned og gjennomgått.

**Løsningsforslag**

**Comment by Elianne** [comment]
Følgende må vurderes: 

- [ ] Fiske, fangst og akvakultur
- [ ] Folkehøgskole
- [ ] Handel og service
- [ ] Opphavsrett
- [ ] Reiselivsnæring
- [ ] Religion og livssyn
- [ ] Studiefinansiering

**Comment by oystein-asnes** [comment]
Religion og livssyn slettes som tema (er uten innhold)

**Comment by oystein-asnes** [comment]
Studiefinansiering endres til tema. emnord blir: studielån , stipend

**Comment by Elianne** [comment]
Enkelte ord står foreldreløse. Må avklares. Forslag til løsning i parantes: 

- [ ] Frisør-, hudpleie-, tatoverings- og hulltakingsvirksomhet (næringsliv)
- [ ] Offentlig innkjøp (Næringsliv)
- [ ] Produktsikkerhet (Nærlingsliv)
- [ ] Servering (Næringsliv)
- [ ] Torgsalg (Fjerne- kjem under bevilling og tillatelser)
- [ ] Alkoholsalg (Fjerne- kjem under bevilling og tillatelser)

**Comment by Elianne** [comment]
Handel og service:
