### ISSUE TITLE
[tema] Endre Forurensning og stråling til Forurensning

### ISSUE THREAD

**Issue by Elianne** [difi/los#257]
Forslag fra Trello: Endre navn på tema til kun Forurensning, og vurdere å legge til Akutt forurensning og Radonmåling.
Løysing:
Endre `Forurensning og stråling` til `Forurensning`. 
Legge til `Akutt forurensning` og `radonmåling`.

Forslag til definisjoner: 
`Akutt forurensning: `
NB: Forurensning av betydning som inntrer plutselig, og som ikke er tillatt.
NN: Forureining med store følgjer som inntrer plutseleg, og som ikkje er tillate.

`Radonmåling`: 
NB: Måling av mengden radongass i inneluft.
NN: Måling av mengda radongass i inneluft.

**Comment by oystein-asnes** [comment]
Forslaget om endre tittel forkastes. Tittel blir `Forurensning og stråling` fordi radonmåling ikke er forurensning (men stråling).
