### ISSUE TITLE
Emneorda Ektefellepensjon og gjenlevendepensjon

### ISSUE THREAD

**Issue by MartaKari** [difi/los#266]
Er relatert til: 

Beskrivelse: `Ektefellepensjon` og `Gjenlevendepensjon `er ei økonomisk yting til gjenlevande. Det ser ut til at Nav brukar gjenlevende og gjenlevendepensjon om pensjonen frå folketrygda, medan SPK, KLP m.fl. brukar ektefellepensjon. Reglane for dei ulike pensjonane er ikkje like for t.d. sambuarar.   

Løysingsforslag: Føreslår at vi vel `Gjenlevendepensjon `som emneord og har `Ektefellepensjon `som hjelpeord.
@jmfurseth

**Comment by jmfurseth** [comment]
@MartaKari - forslaget ditt støttes: 
> Løysingsforslag: Føreslår at vi vel Gjenlevendepensjon som emneord og har Ektefellepensjon som hjelpeord.
