### ISSUE TITLE
Foreldreansvar som hjelpeord til farskapserklæring

### ISSUE THREAD

**Issue by MartaKari** [difi/los#267]
Er relatert til: `Famile og barn`

Beskrivelse: Føreslår at emneordet  `Farskapserklæring `blir hjelpeord under blir `Fastsettelse av foreldreskap`. 

`Foreldreansvar` nytt hjelpeord .

Blir dette rett @jmfurseth ?

**Comment by Elianne** [comment]
Tenker du at `Farskapserklæring `blir _relatert_ ord (ikke hjelpeord)?

**Comment by MartaKari** [comment]
Ja,  `Farskapserklæring`  bør nok vera _relatert_ til `Foreldreansvar`:

https://www.regjeringen.no/globalassets/upload/kilde/bld/skj/2006/0002/ddd/pdfv/268876-q-0199_b_samboeravtale_-utfyllbar.pdf?epslanguage=nb-NO

**Comment by Elianne** [comment]
Løysning: Legge inn `Foreldreansvar `som `hjelpeord `til `Fastsettelse av foreldreskap`, og legge `Farskapserklæring `som `related`.

**Comment by jmfurseth** [comment]
Vi støtter forslaget ditt @Elianne:
> Løysning: Legge inn Foreldreansvar som hjelpeord til Fastsettelse av foreldreskap, og legge Farskapserklæring som related.
