### ISSUE TITLE
Vurdere om Barnetrygd skal vere eige emneord 

### ISSUE THREAD

**Issue by MartaKari** [difi/los#270]
Er relatert til: Familie og barn

Beskrivelse: `Barnetrygd` er no eige emneord, men også hjelpeord under `Ytelser til foreldre og foresatte`.

Løysingsfosrslag:

Stryk det som emneord. Det er ei fullautomatisert teneste. Det er berre dei som kjem frå utlandet som må søka. 

Er du einig @jmfurseth ?

**Comment by jmfurseth** [comment]
`Barnetrygd` er ikke full-automatisert, så bl.a. de som blir enslige må søke. Vi mener dette fortsatt må stå som emneord. 
Se: https://www.nav.no/no/Person/Familie/Barnetrygd+og+kontantstotte/barnetrygd

**Comment by MartaKari** [comment]
Ja, men no ligg `Barnetrygd `både som hjelpeord under `Ytelser til foreldre og foresatte` og som eige emneord. Viss det ikkje er noko problem med å ha ein term både som emneord og hjelpeord til eit anna emneord, støttar eg forslaget.  

Viss det skulle vera problematisk, føreslår eg at vi legg det som eit hjelpeord under `Ytelser til foreldre og foresatte`, på lik linje med andre stønader.

**Comment by Elianne** [comment]
Vi skal ikke ha både emneord og hjelpeord som samme ord. Men, vi kan ha relatert ord og emneord. 
Løsningsforslag: `Barnetrygd ` består som emneord, og relatert ord under `Ytelser til foreldre og foresatte`.

**Comment by jmfurseth** [comment]
@Elianne - dette høres ut som en bra løsning. Ikke sant, @randiaasen?

**Comment by RandiAasen** [comment]
@Elianne @MartaKari @jmfurseth Enig i vurderingen
