### ISSUE TITLE
Livshendelse Starte og drive en frivillig organisasjon

### ISSUE THREAD

**Issue by MartaKari** [difi/los#272]
Relatert til #209 Gjennomgå og kvalitetssikre Livshendelser i Los

Desse emneorda ligg no under Starte og drive en frivillig organisasjon:

- [x] Frivilligsentral
- [x] Lag og foreninger

Altinn har ei eiga nettside Starte og registrere en forening:

https://www.altinn.no/starte-og-drive/starte/registrering/starte-registrere-forening/

Kan den sida brukast, ev. be dei justera/leggja ut meir info? Ev. Frivillig.no?

Frivillig.no er støttet av Gjensidigestiftelsen, Sparebankstiftelsen DNB, Kulturdepartementet, Helsedepartementet og Oslo kommune.

https://www.frivillighetnorge.no/no/kurs_+_verktoy/veiledere/hvordan_starte_en_organisasjon+/

**Comment by Elianne** [comment]
Hvordan tenker du den skal brukes i LOS? @MartaKari

**Comment by MartaKari** [comment]
No ligg desse emneorda der:
- [ ] Frivilligsentral
- [ ] Lag og feoreninger

Andre emneord som kan vere med under `Starte og drive en frivillig organisasjon` :
- [ ] Bingo
- [ ] Idrettsmidler
- [ ] Kulturmidler
- [ ] Lotteri
- [ ] Nærmiljøtilskudd
- [ ] Rapportering for næringsdrivende (Frivillige organisasjonar kan levere inn Samordnet registermelding - Forenklet blankett for foreninger )
- [ ] Tilskudd til friluftsliv
- [ ] Tilskudd til helse og eldre
- [ ] Tilskudd til tro og livssyn
- [ ] Ungdomsmidler

`Politiattest ` (Emnord i Los 2.0 (har vi det i 3.0?) 

(Div. rettleiarar på Frivillighet Norge:
https://www.frivillighetnorge.no/?module=Articles&action=Article.publicOpen&id=1492)
