### ISSUE TITLE
Omsorgslønn og/eller omsorgsstønad - slå saman emneord

### ISSUE THREAD

**Issue by MartaKari** [difi/los#273]
Er relatert til: Sosiale tjenester og Helse og omsorg

Beskrivelse: `Omsorgslønn ` (under Økonomiske ytelser) og `Omsorgsstønad ` (under Avlastning og støtte) er begge emneord. 

Føreslår at `Omsorgsstønad `blir emneord og `Omsorgslønn `hjelpeord. Knyta det til dei to nemnde undertema.  

Blir dette i så fall korrekt @stephanie-lovenskiold  @jmfurseth ?

**Comment by stephanie-lovenskiold** [comment]
Det høres fint ut for meg.

**Comment by jmfurseth** [comment]
Vi så vel ikke denne i gjennomgangen her om dagen, @randiaasen - men å fjerne `Omsorgslønn` som eget emneord og endre til hjelpeord, var en veldig bra løsning, synes jeg? Enig?
