### ISSUE TITLE
Livshendelse Å ha et alvorlig sykt barn

### ISSUE THREAD

**Issue by MartaKari** [difi/los#274]
Relatert til #209 Gjennomgå og kvalitetssikre Livshendelser i Los

Desse emneorda ligg no under Å ha et alvorlig sykt barn:

- [x] Frikort for helsetjenester
- [x] Habilitering og rehabilitering
- [x] Omsorgslønn (forslag om at dette blir hjelpeord #273)
- [x] Personlig assistent
- [x] Skoleskyss
- [x] Støtte til familier
- [x] Sykehus

Andre emneord som kan vera aktuelle:  

- [x] Behandlingsreise
- [x] Fastlege
- [x] Fysioterapi
- [x] Helsestasjon
- [x] Hjemmesykepleie
- [x] Kiropraktikk
- [x] Langvarige helsetjenester
- [x] Legemiddel
- [x] Omsorgsstønad 
- [x] Omsorgsavlastning
- [x] Pasient- og brukerombud (Vurdere dette)
- [x] Pasientskadeerstatning (Vurdere dette)
- [x] Rehabiliteringspenger
- [x] Syketransport
- [x] Ytelser til foreldre og foresatte
- [x] Ytelser ved sykdom i familien

 @jmfurseth @stephanie-lovenskiold

**Comment by stephanie-lovenskiold** [comment]
Flere emneord som kan være aktuelle:

- [ ] Rådgivning og kurs. Def: Tjenester og tilbud til pårørende eller til de som midlertidig eller varig trenger støtte eller avlastning.
- [ ] Støttekontakt. Def: Et tilbud til personer med behov for kontakt, hjelp og støtte i hverdagen.   Støttekontakten tilbyr blant annet sosialt samvær etter behov og følge til   ulike fritidsaktiviteter.
- [ ] Tilrettelagt fritid. Def: Aktiviteter og tilbud for personer med fysisk eller psykisk funksjonsnedsettelse.
- [ ] Legehjelp (legevakt/fastlege) Se #281 
- [ ] Bofellesskap. Def: Kommunalt botilbud til psykisk utviklingshemmede.
- [ ] Dagtilbud. Def: Dagtilbud omfatter aktiviteter rettet mot hjemmeboende eldre, funksjonshemmede, rusavhengige m.fl. Aktivitetene skal gi mulighet for sosialt fellesskap, hindre isolasjon og gi mulighet til økt mestring og utvikling av funksjonsnivå.
- [ ] Klage på helse- og omsorgstjenester

**Comment by Elianne** [comment]
Skuleskyss?

**Comment by MartaKari** [comment]
Også

- [ ] Barnehageplass
- [ ] Besøkshjem
- [ ] Bostøtte
- [ ] Ergoterapi
- [ ] Pedagogisk-psykologisk tjeneste

**Comment by jmfurseth** [comment]
Det er mange emneord som også kan ha betydning i en slik livssituasjon og vi ser mange gode forslag over. En vi ikke ser, er nivå 2 kategorien:
- [ ] Hjelpemidler
Kategorien kan relateres - eller evt. emneordene som er knyttet til legges til?
