### ISSUE TITLE
Arbeidssøking er både tema og emneord - må endrast

### ISSUE THREAD

**Issue by MartaKari** [difi/los#276]
Er relatert til: `Arbeid `og `Arbeidsliv`

`Arbeidssøking` er eit tema under `Arbeid`.

`Arbeidssøking `er eit emneord under `Arbeidsliv`.

Vi må sjå nærmare på dette.

**Comment by Elianne** [comment]
Dette er en feil som henger igjen. Arbeidssøking var bestemt at skulle slettes som emneord. Emneordet blir slettet.

**Comment by MartaKari** [comment]
Kva emneord har vi då som dekker dette?  #173 #276 Eksempel på teneste:

'Søk etter ledige stillinger': https://arbeidsplassen.nav.no/stillinger
