### ISSUE TITLE
Ventestønad - eksisterer ordninga? 

### ISSUE THREAD

**Issue by MartaKari** [difi/los#277]
Er relatert til: Økonomiske ytelser

Beskrivelse: 
"Ventestønad er ein stønad til livsopphald og skal erstatte tapt inntekt når ein har avslutta ein lang dagpengeperiode."

Eksisterer denne ordninga framleis? Får ikkje treff på Nav.no
@jmfurseth

**Comment by jmfurseth** [comment]
Ventestønad - eksisterer ikke, men kan være feilassosiert med ventelønn  - som er avviklet og som finnes som ord i Los v2. 
Forslag: Slettes

**Comment by MartaKari** [comment]
Ventelønn er omtalt på Nav.no - på ei side som er oppdatert august 2019. Så vi bør vel i alle fall ha det som hjelpeord, ev. relatert. Kanskje ikkje så viktig teneste at det bør vera eit eige emneord.

https://www.nav.no/no/Person/Arbeid/Dagpenger+ved+arbeidsloshet+og+permittering/ventel%C3%B8nn
@jmfurseth

**Comment by jmfurseth** [comment]
@MartaKari, @Elianne  og @randiaasen - absolutt enig i at `Ventelønn `ikke skal stå som eget emneord, siden ordningen er utgått. Om det skal stå som hjelpeord og evt. hva den skal stå under, blir da et spørsmål. Hva tror du her, Randi?

**Comment by RandiAasen** [comment]
@MartaKari @Elianne @jmfurseth Ventelønn bør stå som hjelpeord under Inntektssikring, Arbeidssøker eller permittering

**Comment by MartaKari** [comment]
Viss ordninga med `Ventelønn `er utgått, bør vi gje Nav.no tilbakemelding om at dei må oppdatera sidene sine med denne infoen. Og då er det i tilfelle eit spørsmål om vi skal ha det med i Los? Ev. lenka til ei side på Nav.no som seier at ordninga er utgått?

**Comment by jmfurseth** [comment]
Ok, her snakker vi kanskje forbi hverandre litt også. Ordningen `Ventelønn` er avsluttet, så nye tilfeller kommer ikke til. Men, ordningen kan fortsatt ha brukere som mottar ytelser eller personer som søker etter informasjon. Trengs termen i Los da? Her må du gjerne korrigere / fylle ut, @RandiAasen  :-)
