### ISSUE TITLE
Grunnskole for voksne og Grunnskoleopplæring for voksne - slå saman til eitt emneord

### ISSUE THREAD

**Issue by MartaKari** [difi/los#278]
Er relatert til: `Voksenopplæring `og `Grunnskole` 

`Beskrivelse:
 `Grunnskole for voksne` og `Grunnskoleopplæring for voksne` er begge emneord.

Føreslår det første som emneord og det andre som hjelpeord.

**Comment by Elianne** [comment]
Enig, Marta.
