### ISSUE TITLE
Grunnskole for voksne - med to identifikatorar

### ISSUE THREAD

**Issue by MartaKari** [difi/los#279]
Er relatert til: `Voksenopplæring`

Beskrivelse:
`Grunnskole for voksne`  ligg dobbelt i Los, men med ulike identifikatorar: 

http://psi.norge.no/los/ord/grunnskole-for-voksne
http://psi.norge.no/los/ord/videregaende-skole-for-voksne

Føreslår nytt emneord for den siste:

`Videregående opplæring for voksne` 

Nytt hjelpeord: `Videregående skole for voksne`

**Comment by stephanie-lovenskiold** [comment]
Jeg støtter forslaget ditt @MartaKari

**Comment by Elianne** [comment]
Her har det skjedd en feil ved oppretting av nytt emneord. Rettar opp straks.
