### ISSUE TITLE
[ord] Hvem skal ut: Fastlege eller legehjelp?

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#281]
Er relatert til: 

Beskrivelse:
Ser at det er dukket opp 2 emneord som kolliderer. I kommune-forslaget satte vi inn emneordet Legehjelp, som dekker legevakt og fastlege.
I Los 3 slik den ser ut nå, er Fastlege et eget emneord, i tillegg til Legehjelp.

Vi må vurdere om legehjelp er tilstrekkelig, og om vi kan fjerne Fastlege.

**Comment by Elianne** [comment]
Vi fjerner fastlege. Her har vi glemt å lagt inn bestilling på fjerning av fastlege.
