### ISSUE TITLE
Nynorsk og bokmål i identifikatoren - er det eit problem?

### ISSUE THREAD

**Issue by MartaKari** [difi/los#295]
Identifikatoren for Rapportering for næringsdrivende er på nynorsk ('næringsdrivande'):

http://psi.norge.no/los/ord/rapportering-for-naringsdrivande

Andre identifikatorar er på bokmål, f.eks.:
http://psi.norge.no/los/ord/tilsyn-og-kontroll-med-naringsvirksomhet

Er dette eit problem for søk, språkversjonering m.m. @klakegg ?

**Comment by Elianne** [comment]
Eg rettar - skal vera på bokmål.
