### ISSUE TITLE
Bruke æ, ø og å i identifikatorar - er det eit problem?

### ISSUE THREAD

**Issue by MartaKari** [difi/los#298]
Eg ser at i t.d. emneordet Radonmåling har bokstaven -å i identifikatoren:

http://psi.norge.no/los/3/ord/Radonm%C3%A5ling.html

( http://psi.norge.no/los/3/ord/Radonmåling.html )

Er det eit problem @klakegg ?

**Comment by Elianne** [comment]
Dette er ein feil - skal rette opp.

**Comment by MartaKari** [comment]
Ok. Ein -ø her:
http://psi.norge.no/los/3/ord/st%C3%B8nad-til-enslig-fors%C3%B8rger.html

**Comment by MartaKari** [comment]
Ein -æ her:
http://psi.norge.no/los/3/ord/l%C3%A6rling.html

**Comment by MartaKari** [comment]
Nokre identifikatorar med same problem:

http://psi.norge.no/los/3/ord/ytelser-ved-svangerskap,-f%C3%B8dsel,-og-adopsjon.html
http://psi.norge.no/los/3/ord/kontantst%C3%B8tte.html
http://psi.norge.no/los/3/ord/h%C3%B8rselshjelpemidler.html
