### ISSUE TITLE
[ord] Ord som skal inn: Dyrehold (Fritid)

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#344]
Er relatert til: 

Beskrivelse:

**Comment by MartaKari** [comment]
Vi har `Kjæledyr og sportsdyr` som emneord under Fritid (også relatert til `Husdyrhold `og `Smittevern`
http://psi.norge.no/los/3/ord/kjaledyr-og-sportsdyr.html

Så har vi `Husdyrhold `som emneord under Landbruk, relatert til `Kjæledyr og sportsdyr`
http://psi.norge.no/los/3/ord/husdyrhold.html

Føreslår at `Dyrehold `blir eit hjelpeord til `Husdyrhold`. Einig @stephanie-lovenskiold
