### ISSUE TITLE
[ord] Ord som skal inn: Fag- og yrkesopplæring (Videregående oppl)

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#346]
Er relatert til: 

Beskrivelse:

**Comment by Elianne** [comment]
Videregående opplæring heter Videregående skole, men er emneord, ikkje tema. Fag og yrkesopplæring (var ord) er allerede tema og kan ikke legges inn som ord. 

 - Videregående opplæring fjernes som undertema (blir erstattet av Fag- og yrkesopplæring) (sjå sak #59)
