### ISSUE TITLE
[tema] Energi blir til Miljø og energi

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#364]
Er relatert til:

**Beskrivelse** 

**Løsningsforslag**
Temaet Energi blir til Miljø og energi. For vi trenger å få inn Miljøsertifisering som ord.

**Comment by Elianne** [comment]
Konklusjon: Energi forblir energi.
Legge inn Mijø som eige tema - Miljøsertifisering bør vera med som emneord.
