### ISSUE TITLE
[tema] Økonomisk støtte og Økonomiske ytelser

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#365]
Er relatert til:

**Beskrivelse** 

**Løsningsforslag**
Under Sosiale tjenester foreslår jeg at vi slår sammen Økonomisk støtte og rådgivning med Økonomiske ytelser til tema Økonomiske ytelser og rådgivning.

**Comment by oystein-asnes** [comment]
Løsningsforslag i møte 31.01.2019: Vi slår sammen `Økonomisk støtte og rådgivning` med `Økonomiske ytelser` og gir det nytt navn: `Økonomiske ytelser og rådgivning`
