### ISSUE TITLE
Ytelser ved svangerskap, fødsel og adopsjon - endre definisjon 

### ISSUE THREAD

**Issue by MartaKari** [difi/los#375]
Er relatert til: Familieytelser

Beskrivelse: definisjon av disse ytelsene: Adopsjonspenger, Engangsstønad, Foreldrepenger, Svangerskapspenger

Men det ser ikke ut til at det er de ytelsene som er definerte:  

Bidra til å dekke bortfall av arbeidsinntekt for yrkesaktive i forbindelse med barns eller barnepassers sykdom, barns funksjonshemning og pleie av nærstående i livets sluttfase, som omfatter pleiepenger, omsorgspenger, opplæringspenger.

**Comment by Elianne** [comment]
Stemmer - den er feilaktig kommet med fra annet emneord. Her mangler definisjon @jmfurseth

**Comment by jmfurseth** [comment]
Ja, tror teksten var byttet om ja - hvis det var `Familieytelser`. Hva tror du om definisjonstekst @randiaasen? Fant ikke `Familieytelser` i vår interne begrepskatalog, men burde vel strengt tatt vært definert der.

**Comment by oystein-asnes** [comment]
Jeg lukker denne ettersom den er dekket av andre oppgaver knyttet til definisjoner som mangler.
