### ISSUE TITLE
Listevisning av Kommune-Los

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#379]
Er relatert til: #208 
 
Det er behov for en listevisning av Kommune-los slik at det er mulig å se (i en hierarkisk liste) hvilke tema og emneord som inngår i samlingen,

**Comment by klakegg** [comment]
http://psi.norge.no/los/3/view/table-nb/samling/kommune-los
http://psi.norge.no/los/3/view/table-nn/samling/kommune-los
http://psi.norge.no/los/3/view/table-en/samling/kommune-los
