### ISSUE TITLE
Validering av Skos - feilmeldingar

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#384]
Ved bruk av; http://demo.seco.tkk.fi/skosify/skosify/
Status: processing 
Phase 1Parsing input files
Warnings
http://psi.norge.no/los/tema/Miljøsertifisering does not look like a valid URI, trying to serialize this will break.

**Comment by jmfurseth** [comment]
Ok, det er mao. ikke lov med 'ø' i URIer, med mindre det er %-enkodet?
Dvs. at i stedet for `http://psi.norge.no/los/tema/Miljøsertifisering` blir det gyldig (men mindre lesbart) med `http://psi.norge.no/los/tema/Milj%C3%B8sertifisering` (ref. https://urlify.dev/ )
