### ISSUE TITLE
Barnebidrag er både emneord og hjelpeord

### ISSUE THREAD

**Issue by MartaKari** [difi/los#385]
Er relatert til: `Familieytelser`

Beskrivelse: `Barnebidrag `er eige emneord under `Familieytelser `, men også hjelpeord under `Ytelser til foreldre og foresatte`

Her bør ein velja emnoerd og relatert, jf. sak #270 

(Det er fleire hjelpeord under `Ytelser til foreldre og foresatte` som også er eigne hjelpeord, t.d. kontantstøtte. Må sjekkast og så meldast inn som eigne saker. Eg rekk det ikkje no )

**Comment by Elianne** [comment]
Eg har retta opp (inkl dei andre hjelpeorda).
