### ISSUE TITLE
[ord] Slå sammen Studielån og stipend til ett emneord

### ISSUE THREAD

**Issue by Elianne** [difi/los#387]
Beskrivelse: Studielån og stipend er to egne emneord, men har samme definisjon og tilknytning til andre tema/emneord.

Forslag til løsning: 
Slå sammen til ett emneord, Stipend og studielån.

**Comment by Elianne** [comment]
@oystein-asnes

**Comment by oystein-asnes** [comment]
Vi lar denne ligge som den er.
