### ISSUE TITLE
[ord]  Ekteskap er både undertema og emneord

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#395]
Er relatert til: #7 og #8 

**Beskrivelse:** 
`Ekteskap `er nå både et undertema (http://psi.norge.no/los/3/tema/ekteskap.html)  og et eget emneord (http://psi.norge.no/los/3/ord/ekteskap.html)

Forslag til løsning: Ta bort `ekteskap `som emneord  - dette behovet er dekket av emneordet `vielse` ( http://psi.norge.no/los/3/ord/vielse.html)

**Comment by stephanie-lovenskiold** [comment]
Jeg støtter forslaget ditt. I mine notater har jeg allerede gjort akkurat det. Jeg har sikkert bare glemt å lage en issue.

**Comment by MartaKari** [comment]
Då må vi passa på at ekteskap blir eit hjelpeord.
