### ISSUE TITLE
[ord] Fjerne: Barnepark

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#4]
Er ikke del av KS-los
Relatert til #1

**Comment by klakegg** [comment]
Barnepark er tilbudt i flere kommuner (minst 20 i Oslo, 3 i Bergen, 1 i Tromsø), og er et annet tilbud enn barnehage. Foreslår at "Barnepark" beholdes inntil videre.

**Comment by stephanie-lovenskiold** [comment]
Sjekket og OK
