### ISSUE TITLE
[ord] Samlet liste over korrektur til kommune-los

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#403]
Familie og barn

- [x] Barnehage   - innhold og kvalitet må rettes for det står på nynorsk
- [ ] Hjelp ved overgrep skal ikke ligge under Barnevern og foreldrestøtte (mener nå jeg)
- [x] Samboerskap og samlivsbrudd skal begge **ut** av kommune-los

Helse og omsorg
- [x] Tolketjenester **inn** under Avlastning og støtte
- [x] Tilrettelagt arbeidstilbud **inn** under avlastning og støtte
- [x] Akutt forurensning **ut**. Den er fra Los 2
- [x] Behandlingsreise **ut** av helsetjenester
- [x] Rehabilitering **ut** av Helsetjenester
- [x] Ambulerende vaktmester **ut** av omsorgstjenester
- [x] Omsorgsstønad **inn** under Omsorgstjenester

Kultur, idrett og fritid

- [x] Dyrehold **inn** under Fritid
- [x] Lekeplass **inn** under Fritid
- [x] kulturtilbud under Kultur må ha stor K

Natur, klima og miljø

- [x] Naturskadeerstatning  skal **ut** av Kommune-Los og da forsvinner også Lov og rett som tema, for den hører ikke til kommunen.
- [x] Strålevern **ut** fra Forurensning og stråling
- [x] Utslippstillatelse **inn** under Forurensning og stråling
- [ ] Tilskudd til miljøtiltak og Tilskudd til viltformål **inn** under Miljøtilskudd
- [x] Tilskudd til friluftsliv **ut** fra Naturforvaltning
- [x] Turløyper **ut** fra naturforvaltning
- [x] Plantedyrking **inn** under naturforvaltning

Skole og utdanning

- [ ] Fag- og   yrkesopplæring er ikke et tema men et ord under VGS

- [x] Bibliotektjenester **ut** fra grunnskole
- [x] Brukermedvirkning i skolen **inn** under grunnskole
- [x] Ferie og fridager **inn** under grunnskole
- [x] Karakterer og evaluering **inn** under grunnskole
- [x] Permisjon og fritak **inn** under grunnskole
- [x] Skolehelsetjeneste **inn** under grunnskole
- [x] Skolemiljø **inn** under grunnskole
- [x] Skoletilhørighet **inn** under grunnskole
- [ ] Språkopplæring **inn** under grunnskole
- [x] Tilpasset opplæring **inn** under grunnskole

- [x] Pedagogisk-psykologisk tjeneste skal også **inn** under Voksenopplæring
- [ ] Fag- og yrkesopplæring **inn** under VGS
- [x] Videregående opplæring **inn** under VGS

Sosiale tjenester

- [x] Økonomisk rådgivning **inn** under Økonomiske ytelser og rådgivning
- [x] Sykehjem **ut** av Botilbud
- [x] Lærling **inn** under Kvalifisering til arbeid

Trafikk og transport

- [x] Motorferdsel i utmark **ut** av Kjøretøy
- [x] Førerkort og sertifikat som tema skal **ikke med** i kommune-los. 
- [x] Miljøvennlig transport **inn** under Mobilitetstilbud
- [x] Reisegaranti **inn** under Mobilitetstilbud
- [x] Miljøvennlig transport **inn** under veg og vegregulering

:)))

**Comment by stephanie-lovenskiold** [comment]
Jeg ser at jeg har skrevet noe feil over. Jeg har skrevet at Hjelp ved overgrep skal ut fra Barnevern, men ser i tidligere notater at vi la den inn. Så den er OK.

**Comment by oystein-asnes** [comment]
*  Har slettet `Ambulerende vaktmester` fra Los - var definert som en kommunal tjeneste
* `Tilskudd til miljøtiltak` mangler - må opprettes
* `Språkopplæring` mangler - må opprettes
* Får ikke fjernet `Førerkort og sertifikat` ennå. Her er det noen underliggende emneord som er relatert til kommune-Los (Firehjuling, vannskuter mv)

**Comment by oystein-asnes** [comment]
1. Er `Tilskudd til miljøtiltak` noe annet enn `Miljøtilskudd` @stephanie-lovenskiold ?
2. Temaet `Språk` er fjernet fra v3.0, hvor skal ev. `Språkopplæring` innplasseres?

**Comment by oystein-asnes** [comment]
Forslag til løsning på  `Førerkort og sertifikat`: 
1. Fjerne emneordene `Firehjuling`, `Snøskuter `og `Vannskuter` fra Los, ettersom `Motorferdsel i utmark` dekker behovet til kommunene om regulering av aktivitet (min påstand). De fremstår også som vilkårlige ettersom andre typer køretøy ikke er med. 

2.  Vi endrer beskrivelsen av `Firehjuling`, `Snøskuter `og `Vannskuter` (de er veldig kommune-sentrert), og fjerner de fra samlingen `Kommune-Los`, men lar de ligge som emneord under temaene `Kjøretøy` og `Førerkort og sertifikat`.

Kom gjerne med innspill @stephanie-lovenskiold og @hildea

**Comment by stephanie-lovenskiold** [comment]
> Er Tilskudd til miljøtiltak noe annet enn Miljøtilskudd @stephanie-lovenskiold ?
> Temaet Språk er fjernet fra v3.0, hvor skal ev. Språkopplæring innplasseres?

Jeg la inn Miljøtilskudd som et nytt undertema fordi den var forsvunnet. Det var tidligere et tema som het Miljø og energi, men det ble til Energi. Dermed mistet vi Miljø som tema. Og jeg trengte å plassere miljøtilskudd. Løsningen ble Miljøtilskudd som tema og Tilskudd til miljøtiltak som emneord.
Kommenter det gjerne.

Språkopplæring var tenkt skulle ligge som et emneord under tema Grunnskole. Det dekker tjenestene morsmålsopplæring og særskilt språkopplæring for minoritetsspråklige.

**Comment by stephanie-lovenskiold** [comment]
> Forslag til løsning på  Førerkort og sertifikat:
> 
> 
> Fjerne emneordene Firehjuling, Snøskuter og Vannskuter fra Los, ettersom Motorferdsel i utmark dekker behovet til kommunene om regulering av aktivitet (min påstand). De fremstår også som vilkårlige ettersom andre typer køretøy ikke er med.
> 
> 
> Vi endrer beskrivelsen av Firehjuling, Snøskuter og Vannskuter (de er veldig kommune-sentrert), og fjerner de fra samlingen Kommune-Los, men lar de ligge som emneord under temaene Kjøretøy og Førerkort og sertifikat.
> 
> 
> Kom gjerne med innspill @stephanie-lovenskiold og @hildea

Jeg tror jeg er enig med deg Øystein. Jeg har plassert `Motorferdsel i utmark` under `Naturforvaltning`. Kommunen har ingen andre reguleringer for kjøretøyene enn den om ferdsel, så … det må være greit. Da vil temaet `Kjøretøy` i Kommune-los inneholde ordene `Elbil`, `Piggdekk` og `Vrakpant`.

**Comment by oystein-asnes** [comment]
Vi trenger avklaringer på #422 og #423 før vi kan lukke denne @stephanie-lovenskiold
