### ISSUE TITLE
[tema] Tomme undertema og emneord som er knyttet til feil nivå

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#407]
Følgende undertema har ingen emneord: 

* `Reiselivsnæring` http://psi.norge.no/los/3/tema/reiselivsnaring.html
* `Integrering` http://psi.norge.no/los/3/tema/innvandring-og-integrering.html

Følgende emneord ligger nå rett under hoveddetamet `Skatt og Avgift`:
* `Betaling av skatt` http://psi.norge.no/los/ord/betaling-av-skatt
* `Oppgaveplik`t http://psi.norge.no/los/ord/oppgaveplikt
* `Skatteattest` http://psi.norge.no/los/ord/skatteattest

**Comment by Elianne** [comment]
Reiselivsnæring og integrering skal utgå. Se issue #250 og Trello (reiselivsnæring)

**Comment by oystein-asnes** [comment]
Fikset :-)
