### ISSUE TITLE
[ord] Oppgaveplikt er feilplassert

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#412]
Er relatert til: #407 

`Oppgaveplikt` ligger nå direkte under nivå i `Skatt og avgift` http://psi.norge.no/los/3/ord/oppgaveplikt.html noe som er en feil.  I Los 2.0 lå dette under næringsutvilking. 

Skal `Oppgaveplikt`  fjernes eller flyttes til `Næringsutvikling`?

**Comment by stephanie-lovenskiold** [comment]
Jeg mener det skal fjernes. I hvertfall ihht forslaget jeg sydde sammen for Næring. For der ble alt løftet opp et hakk. Slik at kravet/tjenesten kommer under emneordet Rapportering for næringsdrivende.
