### ISSUE TITLE
Høyringssvar frå Språkrådet

### ISSUE THREAD

**Issue by OleVaage** [difi/los#414]
**Beskrivelse av behovet/problemet**:
Nokre av dei nynorske emneorda i LOS har ein skrivemåte som avvik frå rettskrivingsnormalen. 

**Forslag til løsning**:

- [x] Sjukefråver > Sjukefråvær (ev. sjukefråvære)
- [x] Betalingssatser for kommunale tjenester > Betalingssatsar for kommunale tenester
- [x] Medverkand >  Medverknad
- [x] Barnehage - innhold og kvalitet > Barnehage – innhald og kvalitet
- [x] Familieytelsar > Familieytingar
- [x] Ytelsar til gjenlevende > Ytingar til attlevande
- [x] Ytelsar ved sjukdom i familien > Ytingar ved sjukdom i familien
- [x] Avlastning og støtte > Avlasting og støtte
- [x] Tilrettelagt arbeidstilbod > Tilrettelagd arbeidstilbod
- [x] Akutt forurensning > Akutt ureining (ev. Akutt forureining)
- [x] Friskliv og mestring > Friskliv og meistring
- [x] Helsesykepleier > Helsesjukepleiar
- [x] Langevarige helsetjenester > Langvarige helsetenester
- [x] Tilrettelagt transport > Tilrettelagd transport
- [x] Hjelp ved rusavhengighet > Hjelp ved rusavhengnad (ev. Hjelp ved rusavhengigheit)
- [x] Dyrehold > Dyrehald
- [x] Tilrettelagt fritid >Tilrettelagd fritid
- [x] Lokaler og idrettsanlegg > Lokale og idrettsanlegg
- [x] Meinerstatning > Meirestatning
- [x] Rettsvesen > Rettsstell
- [x] Namsmyndigheit > Namsmakt
- [x] Akutt forurensning > Akutt ureining (ev. Akutt forureining)
- [x] Bekymringsmelding om brannsikkerhet > Bekymringsmelding om branntryggleik
- [x] Repetisjonstjeneste > Repetisjonsteneste
- [x] Blåskjellvarsel > Blåskjelvarsel
- [x] Vidaregående skule > Vidaregåande skule
- [x] Fråver > Fråvære (Ev. Fråvær)
- [x] Økonomiske ytelser og rådgjeving > Økonomiske ytingar og rådgjeving
- [x] Båt, havn og kyst > Båt, hamn og kyst
- [x] Tilrettelagt transport > Tilrettelagd transport

Ole Våge
Språkrådet

**Comment by oystein-asnes** [comment]
Tusen takk for tilbakemelding @OleVaage. Vi skal ordne dette snarast.
