### ISSUE TITLE
Skille mellom definisjoner og kommentarer

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#418]
Er relatert til: #419 

**Beskrivelse** 
Flere definisjoner er ikke definisjoner, men bruksbeskrivelser. Dette må ogå ses i sammenheng med definisjoner i begrepskatalogen. Prosess for å harmonisere begrep. 

**Løsningsforslag**
Skille mellom definisjoner og bruksbeskrivelser i datamodellen. (For eksempel ved hjelp av Skos:definition og Skos:note).

**Comment by jmfurseth** [comment]
Interessant for oss prinsipelt, men kanskje ikke alle definisjoner / kommentarer. Tenker vi burde ta en prat "hjemme" med Silje, @randiaasen
