### ISSUE TITLE
[ord] Opprette Tilskudd til miljøtiltak som emneord

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#422]
Er relatert til: #350 , #403 
Opprette `Tilskudd til miljøtiltak` som emneord  knyttet til temaet `Miljøtilskudd`.

**Comment by Elianne** [comment]
Skal dette da erstatte ordet Miljøtiltak som ligger under Miljøtilskudd? Se #360 @stephanie-lovenskiold  @oystein-asnes

**Comment by oystein-asnes** [comment]
> Skal dette da erstatte ordet Miljøtiltak som ligger under Miljøtilskudd? Se #360 @stephanie-lovenskiold @oystein-asnes

Vi kan uansett ikke ha `Miljøtiltak` som emneord  under `Miljøtilskudd`. Dersom vi trenger å skille mellom _tilskudd_ og _tiltak_ foreslår jeg at:
1)  vi flytter `Miljøtiltak` inn under `Miljø`, og 
2) oppretter `Tilskudd til miljøtiltak` som nytt emneord under `Miljøtilskudd`. 

Du får siste ord her @stephanie-lovenskiold.

**Comment by stephanie-lovenskiold** [comment]
Jeg er litt forvirret. Her er hvordan jeg tenkte det skulle bli:

**Miljøtilskudd**
Tilskudd til friluftsliv
Tilskudd til miljøtiltak
Tilskudd til viltformål

Miljøtilskudd er da et undertema til Natur, klima og miljø.
Jeg opprettet saken da jeg oppdaget at vi ikke hadde noe emneord for tilksudd til miljø. Såvidt jeg husker.

**Comment by oystein-asnes** [comment]
Vi er enige, men det henger fortsatt litt i luften om `Miljøtiltak` være eget emneord i tillegg til `tilskudd til...` Det må i så fall ligge her: https://psi.norge.no/los/3/tema/miljo.html

**Comment by stephanie-lovenskiold** [comment]
Aha NÅ skjønner jeg. `Miljø` skal vel bort. Jeg trodde `Miljø` var fjernet for lengst. Derfor trengte vi `Miljøtilskudd`. `Miljø` ligger ikke i listevisningen https://psi.norge.no/los/3/view/table-nb/samling/kommune-los

**Comment by oystein-asnes** [comment]
Nå er det min tur å være forvirret :-)  Hvis vi fjerner `Miljø` (undertema) så må `Miljøsertifisering` enten fjernes eller flyttes. (Det mest logiske er i så fall å flytte det til `Sertifisering og autorisasjon` under `Næring`)

Mitt spørsmål var om `Miljøtiltak` skal bort eller flyttes inn under `Miljø`.

**Comment by stephanie-lovenskiold** [comment]
Ja, men `Miljø` som undertema _er_ fjernet i kommune-los.
Og `Miljøsertifisering` ligger under `Sertifisering og autorisasjon`.


Svaret på spørsmålet er:
 Det skal være et emneord som heter `Tilskudd til miljø/Tilskudd til miljøtiltak` og ordet skal ligge under temaet `Miljøtilskudd`.


Ser forresten en skrivefeil. Det står Miljøstilskudd. Fjerne s-en.

**Comment by Elianne** [comment]
Hm.. `Miljø `ligger under `Natur, klima og miljø` i LOS, men de har tatt det bort fra kommune-LOS-ok. Men, `Miljøsertifisering `ligger i dag under temaet `Miljø`, ikke `Sertifisering og Autorisasjon,` da det ikke er tema, men ord - se #236

Du vil altså at `Sertifisering og autorisasjon` skal være et undertema til `Natur, klima og miljø`, og deretter legge `Miljøsertifisering `under der igjen?

**Comment by stephanie-lovenskiold** [comment]
Ja jeg ser at jeg har forklart meg helt feil. `Miljøsertifisering` er borte/fjernet som eget emneord. Det er blitt erstattet av det bredere emneordet `Sertifisering og autorisasjon`. Men det betyr at informasjon om miljøsertifisering kan plasseres under `Sertifisering og autorisasjon`.

Svaret på det siste spørsmålet er Nei. bare la `Sertifisering og autorisasjon` ligge der det ligger, under Næringsliv.

**Comment by Elianne** [comment]
Problemet er at Sertifisering og autorisasjon er et emneord - det kan ikkje legges noe under Sertifisering og autorisasjon - med mindre du vil at det skal være et underTEMA? Spørsmålet er : Skal vi endre Sertifisering og autorisasjon fra å være, i dag, et ord, til å bli et tema?

**Comment by stephanie-lovenskiold** [comment]
Jeg vet. Jeg mente bare at man plasserer tjenester og informasjon til et emneord. altså etterpå, når man skal bruke Los på en nettside. Og informasjon om miljøsertifisering kan plasseres under/tagges med Sertifisering og autorisasjon. Og så kan vi ha miljøsertifisering som skjult søkeord.

**Comment by oystein-asnes** [comment]
Jeg tror det er viktig å diskutere ut fra hva som ligger [i hele Los](https://psi.norge.no/los/3/struktur.html), slik at vi ikke snakker forbi hverandre 

Da blir det slik (?):

1. [Miljøsertfisering](https://psi.norge.no/los/3/ord/miljosertifisering.html) slettes og legges til som hjelpeord til [Sertifisering og autorisasjon](https://psi.norge.no/los/3/ord/sertifisering-og-autorisasjon.html) 
2. [Miljøtiltak](https://psi.norge.no/los/ord/miljotiltak) endres til `Tilskudd til miljøtiltak`
3. Undertemaet [Miljø](https://psi.norge.no/los/tema/miljo) fjernes fra Los (det blir uten innhold)

Er vi enige om dette @MartaKari @stephanie-lovenskiold @Elianne ?

**Comment by stephanie-lovenskiold** [comment]
Eg er heilt enig.
Og beklager rotet.

**Comment by MartaKari** [comment]
Eg støttar også forslaget. Så kan vi leggja inn dette eller eit liknande ord dersom det skulle bli behov for det.
