### ISSUE TITLE
[ord] Opprette språkopplæring som nytt emneord

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#423]
Er relatert til: #403 #112 

Opprett `Språkopplæring` som emneord knyttet til undertemaet `Grunnskole` og legg dette til i samlingen kommune-los.

**Comment by oystein-asnes** [comment]
Er dette noe annet en retten til særskild språkopplæring @stephanie-lovenskiold ? http://www.nyinorge.no/no/Ny-i-Norge-velg-sprak/Ny-i-Norge/Barn-og-skole/Skolesystemet/Mottaksskoler-og-mottaksklasser/ 

Hvis ikke,  må vi vurdere å heller bruke `Særskild språkopplæring` . Noen andre som har mening om dette? @maasgaard @MartaKari

**Comment by stephanie-lovenskiold** [comment]
Det jeg hadde tenkt var en fellesbetegnelse på språkopplæring for minoriteter, og morsmålsopplæring, og kanskje andre typer som dukker opp etter hvert. Tenkte det var smart med et ord som dekker bredt.
Men hører gjerne på motargumenter.

**Comment by MartaKari** [comment]
`Språkopplæring` kan jo vera vanleg norskopplæring, opplæring i framandspråk for norsktalande elevar osv. Dersom vi med `språkopplæring `meiner  språkopplæring for minoritetar, tykkjer eg at termen er litt for vid.

**Comment by stephanie-lovenskiold** [comment]
Vi kan godt gå for `Særskilt språkopplæring`.

**Comment by oystein-asnes** [comment]
Konklusjon:
Legg til `Særskilt språkopplæring` / `Særskild språkopplæring` / `Special language training` som nytt emneord knyttet til undertemaet `Grunnskole` med følgende definisjon (forslag basert på [Udir.no](https://www.udir.no/laring-og-trivsel/minoritetsspraklige/regleverk-som-gjelder-spesielt-for-minoritetsspraklige/sarskilt-sprakopplaring/Hva-betyr-retten-til-sarskilt-sprakopplaring/)):

Forsterket opplæring i norsk inntil eleven har fått tilstrekkelige norskferdigheter til å følge den ordinære opplæringen i skolen. Om nødvendig har eleven også rett til tospråklig fagopplæring og morsmålsopplæring.
