### ISSUE TITLE
[ord] Endre Bolignummer til Bruksenhetsnummer  

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#428]
Er relatert til: #205 

**Definisjon/beskrivelse:**
Bruksenhetsnummeret består av en bokstav og fire siffer som entydig identifiserer den enkelte bruksenhet (f.eks. leilighet) innenfor en adresserbar bygning eller bygningsdel.  Alle leiligheter skal ha sin egen adresse, på lik linje med eneboliger.

**Preferred:**
en: Dwelling number
nn: Brukseinheitsnummer (?) 

**Hjelpeord:**
nb: Adresse, Boligregister, Bolignummer
nn: Adresse,  Bustadregister, Bustadnummer

**Comment by Elianne** [comment]
Forslag til NN: Brukseiningsnummer
