### ISSUE TITLE
Barnehage

### ISSUE THREAD

**Issue by Margretheas** [difi/los#440]
Er relatert til: 

Beskrivelse:
Jobber med en kunde hvor vi nå er i gang med å implementere Los på deres nettsted. En tilbakemeldingen jeg har fått er som følgende:

_Barnehage bør ligge under skole og utdanning, da det er første del av utdanningsløpet.
At barnehage ligger under "Barn og familie" er et foreldet syn. Tidligere lå bhg under barne- og familiedep, men vi har vært i kunnskapsdep nå i mange år._

Kunne jeg ha fått en tilbakemelding på hvorfor dere har valgt å ikke legge barnehage under Skole og utdanning?

**Comment by stephanie-lovenskiold** [comment]
Hei
Jeg vet ikke om jeg kan begrunne hvorfor _Barnehage_ ble liggende under _Barn og familie_ og ikke under under _Skole_. Sannsynligvis fordi _Skole_ og _utdanning_ ble gruppert sammen fremfor _Oppvekst og skole_, som jeg mener å huske at vi vurderte.
Tilbakemeldingen er fin og vi bør vurdere om vi skal flytte Barnehage. Men det har sikkert konsekvenser for Los-strukturen ellers så vi bør vel diskutere det først.

**Comment by oystein-asnes** [comment]
Vedtak i møte 30.06.2021
Vi ser behovet for å knytte `Barnehage `til `Skole og utdanning` fra tjenestetilbyder-perspektivet, men vår påstand er at brukerne ikke først og fremst vil lete etter `Barnehage ` under `Skole og utdanning`. Los har brukerperspektivet som førende prinsipp.  Forslaget avvises.
