### ISSUE TITLE
[ord] Opprette Tolk

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#45]
Relatert til #35 og #39 
KS-Los: *Demokrati og innbyggerrettigheter->Åpenhet->Tolk*
Forslaget er i konflikt med Los 2.0  *Innvandring og integrering->Integrering->Tolketjeneste*

**Comment by oystein-asnes** [comment]
Definisjonen i KS sitt forslag er for snever: "En kommunal tjeneste for de som ikke snakker godt nok norsk til å kommunisere med kommunen."

1. Vi foreslår å beholde `Tolketjenester `som term. Dette er relevant for en hel rekke temaer (Lov og rett, Skole, Helse og omsorg, Innbyggerrettigheter, Integrering). Ny definisjon er påkrevd.
2. Vi foreslår å ikke legge Tolketjenester til `Åpenhet`, men derimot `Medvirkning`
3. Vi stiller spørsmål ved behovet for Tegnspråkstolk som eget emneord. Vi foreslår `Tegnspråktolk `som skjult søkeord til `Tolketjenester`

Kommentarer @stephanie-lovenskiold , @klakegg , @jmfurseth ?

**Comment by jmfurseth** [comment]
> Definisjonen i KS sitt forslag er for snever: "En kommunal tjeneste for de som ikke snakker godt nok norsk til å kommunisere med kommunen."
> 
> 1. Vi foreslår å beholde `Tolketjenester `som term. Dette er relevant for en hel rekke temaer (Lov og rett, Skole, Helse og omsorg, Innbyggerrettigheter, Integrering). Ny definisjon er påkrevd.
> 2. Vi foreslår å ikke legge Tolketjenester til `Åpenhet`, men derimot `Medvirkning`
> 3. Vi stiller spørsmål ved behovet for Tegnspråkstolk som eget emneord. Vi foreslår `Tegnspråktolk `som skjult søkeord til `Tolketjenester`
> 
> Kommentarer @stephanie-lovenskiold , @klakegg , @jmfurseth ?

I samråd med Randi, er meldingen fra Nav at vi kan stille oss bak dette forslaget.

**Comment by Elianne** [comment]
Løsning: 

- [ ] Legge `Tolkestjenester `til Medvirkning
- [ ] Legge `Tegnspråkstolk `som skjult søkeord til `Tolketjenester`
