### ISSUE TITLE
[ord] Endre Overgrep

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#51]
Relatert til #46 #47 
KS-Los:  *Helse og omsorg->Akutt hjelp->Overgrep*
Los 2.0:  *Barn og familie->Barnevern og familievern->Overgrep*

**Comment by oystein-asnes** [comment]
Temaene har endret navn. Denne skal relateres til *Familie og barn-> Barnevern og foreldrestøtte* og tema/akutt-hjelp

**Comment by stephanie-lovenskiold** [comment]
Sjekket ok OK
