### ISSUE TITLE
[tema] Endre Avlastning og støtte

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#52]
Er relatert til: #46 
KS-Los: *Helse og omsorg->Avlastning og støtte*
Los 2.0: *Omsorg, trygd og sosiale tjenester->Avlastning og støtte*

**Comment by oystein-asnes** [comment]
Denne må ses i sammenheng med ord/stotte-til-familier ( *Familie og barn->Barnevern og foreldrestøtte->Støtte til familier*). 
Definisjon Støtte til...: Rådgjeving eller forskjellige former for avlasting til familiar som er sårbare og som treng hjelp.

**Løsningsforslag**:
*Støtte til familier* relateres til både *Familie og barn->Barnevern og foreldrestøtte* og *Helse og omsorg)-> Avlastning og støtte*

**Comment by oystein-asnes** [comment]
Avlastningsbolig (fjernes)
Avlastningshjem (fjernes)
Døvetolk (endres til hidden label forTegnspråktolk)
Hjelpemidler (endres til undertema)
Korttidsopphold
Ledsager (endres til skjult søkeord til ledsagerbevis)
Personlig assistent
Støttekontakt (Hidden: Fritidskontakt)
Tilrettelagt fritid
Dagtilbud (fra Hjemmetjenester)

**KS foreslår i tillegg:**
Avlastning (endres til omsorgsavlastning?)
Ledsagerbevis
Omsorgsstønad
Rehabilitering
Rådgivning og kurs
Tilrettelagt arbeidstilbud
Tolk i helsetjenesten/tolk (NAV: Tegnspråktolk)

**Comment by Elianne** [comment]
Kan denne lukkast, @oystein-asnes ?
