### ISSUE TITLE
[tema] Konflikt  mellom "Bolig og eiendom", KS "Bolig og sosiale tjenester" og KS "Planer, bygg og eiendom"

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#54]
Er relatert til: #18, #31, #32, #33  

**Beskrivelse** 
KS "Bolig og sosiale tjenester" har en tittel som tilsynelatende overlapper med "Bolig og eiendom". Samtidig har KS "Planer, bygg og eiendom" som samsvarer med "Bolig og eiendom" 

 "Bolig" har i KS sitt forslag betydningen *kommunale botilbud*.  

**Løsningsforslag**
- Forkaste forslaget om nytt navn "Bolig og sosiale tjenester" og løse dette behovet i egen oppgave #x
- Endre navn på eksisterende Los-kategori fra **Bolig og eiendom** til **Planer, bygg og eiendom**

**Comment by oystein-asnes** [comment]
Los "Bolig og eiendom" endres til "Bygg og eiendom" og slås sammen med KS "Planer, bygg og eiendom"

**Comment by oystein-asnes** [comment]
Navn på temaene blir `Bygg og eiendom` og  `Sosiale tjenester`.

**Comment by MartaKari** [comment]
Til spørsmålet om undertemaet Sosiale tenester:
Dersom vi utvidar temanamnet, kan sosiale tenester vera eit undertema. Temanamn kan vera 'Pensjon og sosiale tenester', Pensjon, trygd og sosiale tenester' (regjeringa.no)
