### ISSUE TITLE
[ord] Legge til Tilsyn og godkjenning

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#6]
Denne må vurderes nærmere. Begrepet er generisk (kan feks gjelde skjenkeløyver, universell utforming mm) men definisjonen er spesifikt knytt til barnehage: "Kommunen fører tilsyn med private og kommunale barnehager og skal godkjenne barnehager under oppføring."

Løsningsforslag 1: Endre ord til Barnehage - Tilsyn og godkjenning
Løsningsforslag 2: Endre ord til Barnehagetilsyn, og presisere i definisjonen at godkjenning er en del av dette.

**Comment by klakegg** [comment]
"Tilsyn og godkjenning" vil kludre til bruk av Los for søkemotoroptimalisering - brukerne søker på "godkjenning" og opplever at man "alltid" får opp barnehagerelaterte treff.

Noen løse tanker:
* Barnehagetilsyn (samme som over)
* Barnehageadministrasjon (tyngende, ikke foretrukket fra min side)
* Barnehageforvaltning (foretrukket fra min side)

Det å bygge på med ekstra ord i for å forklare hva man mener er uheldig, så min anbefaling er rett og slett "Barnehageforvaltning".

**Comment by oystein-asnes** [comment]
Er relatert til #1

**Comment by oystein-asnes** [comment]
Foreslår *Tilsyn og godkjenning av barnehager*

**Comment by oystein-asnes** [comment]
Endres til *Tilsyn og godkjenning av barnehager*

**Comment by stephanie-lovenskiold** [comment]
Sjekket og ok
