### ISSUE TITLE
[tema] Endre navn på "Trafikk, reiser og samferdsel"

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#60]
KS foreslår å endre navn til "Trafikk, reiser og vei". 
En sammenstilling av Los 2.0 og KS sitt forslag: https://trello.com/b/J01xtwS1

**Comment by oystein-asnes** [comment]
Forslaget ekskluderer ikke-kommunal infrastruktur som for eksempel jernbane og flytransport og bør avvises eller endres.

**Comment by marittor** [comment]
Alt 1. Forslag: Trafikk, reiser og vei beholdes, og det foreslås å opprette en ny kategori som heter "kommunikasjon og infrastruktur" på nivå 1. En slik ny kategori vil muligens medføre endringer også i undertema for andre tema. F .eks vann og avløp kan hete "oppkobling og forts ligge under eiendom, mens under infrastruktur kan undertema/emneord hete "Bygge ..."

Alt 2: Forslag: Beholde: Trafikk, reiser og samferdsel, og lage nytt tema IT og kommunikasjon (droppe termen infrastruktur) på nivå 1. 

Alt 3: Forslag: Nytt hovedtema Trafikk og infrastruktur - Omfatter også vei og en rekke andre undertema.

Etter endt diskusjon går vi for alternativ 3.

**Comment by oystein-asnes** [comment]
Undertemaet "Båt og havn" i KS sitt forslag kuttes til fordel for eksisterende Los-tema "Båttrafikk"

**Comment by oystein-asnes** [comment]
Dette temaet henger sammen med etablering av "NAP" - en egen portal for transportdata (ITS-direktivet). Ettersom NAP i praksis er et filter ned i Felles datakatalog (og bruker samme reg. løsning) , må behovene til Statens vegvesen ivaretas.

**Comment by oystein-asnes** [comment]
Forslag fra SVV: Endre navn til "Trafikk og transport". 
Endringer i undertema:
- Fjerne IT og kommunikasjon
- Skille "veg og vegtrafikk" i to separate undertema
- Endre navn på undertema "kollektivtransport" til "transporttilbud" 
- Omgjøre Godtransport til hidden label
- Yrkestransport som undertema

**Comment by oystein-asnes** [comment]
Konklusjon: Temaet skifter navn til "Trafikk og transport". Forslaget til SVV legges til grunn for undertema og emneord:  https://docs.google.com/spreadsheets/d/1llKIldetOMDRBqC5XlgE3mQqzU2OefoKxxQttzMa6rU/edit?usp=sharing

**Comment by oystein-asnes** [comment]
Denne erstattes av #77

**Comment by oystein-asnes** [comment]
Denne lukkes og erstattes av #77
