### ISSUE TITLE
[tema] Endringer i "Helse"

### ISSUE THREAD

**Issue by klakegg** [difi/los#71]
"Helse" gjøres om til "Helse og omsorg", og skal ha følgende undertema:

* Avlastning og støtte (eksisterer)
* Folkehelse (eksisterer - oppdatere emneord)
* Helsetjenester (eksisterer - oppdatere emneord)
* Pasientrettigheter (eksisterer)
* Psykisk helse (eksisterer)
* Svangerskap og fødsel (eksisterer)
* Akutt hjelp (ny)
* Avlastning og støtte (ny)
* Begravelser (ny)
* Rusomsorg (ny)
* Hjemmetjenester (eksisterer - oppdatere emneord)

**Comment by stephanie-lovenskiold** [comment]
Har foreslått et annet emneord under Rusomsorg. Tidligere Fritidsaktiviteter og tidligere Livsmestring blir til: Aktiviteter og livsmestring for rusavhengige.

**Comment by oystein-asnes** [comment]
I tillegg foreslås det å legge til undertemaet `Hjelpemidler` med følgende emneord:
- Bevegelseshjelpemidler
- Hørselshjelpemidler
- Kommunikasjon og kognisjon
- Synshjelpemidler

**Comment by oystein-asnes** [comment]
> Har foreslått et annet emneord under Rusomsorg. Tidligere Fritidsaktiviteter og tidligere Livsmestring blir til: Aktiviteter og livsmestring for rusavhengige.

Betyr dette av `Rusomsorg` bare får dette ene emneordet @stephanie-lovenskiold ? I KS-forslaget er det tre:

- Fritidsaktiviteter
- Hjelp ved rusavhengighet
- Livsmestring

**Comment by oystein-asnes** [comment]
`Begravelser` ser for meg ut som et duplikat av `Dødsfall og gravferd` (under Familie og barn). Skal undertemaet knyttes til begge (dette bli i så fall første gang vi knytter et undertema til to hovedtemaer)

**Comment by stephanie-lovenskiold** [comment]
Nei begravelser skal vekk fra helse. temaet skal kun ligge under familie og barn. Vi snakket om det en gang for ganske lenge siden.

**Comment by stephanie-lovenskiold** [comment]
Under rusomsorg skal disse to emneordene ligge:

Aktiviteter og   livsmestring for rusavhengige
Hjep ved rusavhengighet

**Comment by oystein-asnes** [comment]
Det er foreslått å endre `Rusomsorg `til `Rus og avhengighet` og at `Spillavhengighet` flyttes hit. I tillegg vi dette undertemaet innholde...

- [ ] Aktiviteter og livsmestring for rusavhengige
- [ ] Hjep ved rusavhengighet

++
