### ISSUE TITLE
Konflikt: Svangerskap og fødsel

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#72]
KS har Jordmor og svangerskapsomsorg som et emneord under tema helsetjenester. Difi har Svangerskap og fødsel som et undertema.

**Comment by oystein-asnes** [comment]
Her er det vel _svangerskapsomsorg_ som er tjenesten, og så kan brukeren selv velge om det er fastlege eller jordmor (ev. jordfar) som skal yte tjenesten. Jeg foreslår derfor å forenkle navnet til  `Svangerskapsomsorg` og legge til `Jordmor` som skjult søkeord. 

Under Los 2.0-temaet `Svangerskap og fødsel` ligger nå `Abort`, `Prevensjon `og `Ufrivillig barnløshet` men ikke noe om selve "jordmor-tjenesten". Her er det forresten  mulig at `Farskapserklæring `og `Fødselsmelding` bør legges til.

Veldig mange av emneordene under `Helse og omsorg` vil kunne relateres til undertemaet `Helsetjenester` (det samme gjelder vel også `Omsorgstjenester`).  Jeg tenker at det er bedre å beholde undertemaet `Svangerskap og fødsel` og heller leve med at mange av emneordene også er relatert til `Helsetjenester`. 

**Løsningsforslag**: 

- [ ] `Svangerskap og fødsel` beholdes som eget undertema (det kan ev. defineres ut av kommune-Los)
- [ ] Emneordet  `Svangerskapsomsorg` legges til og relateres både til både `Helsetjenester `og `Svangerskap og fødsel`

**Comment by stephanie-lovenskiold** [comment]
Høres veldig bra ut. Jeg støtter også forslaget ditt om at farskapserklæring legges hit. Synes å huske at den passet dårlig inn under Familieytelser.

**Comment by oystein-asnes** [comment]
`Søknad om medmorskap` bør også vurderes inn her.
