### ISSUE TITLE
[tema] Konflikt: Psykisk helse

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#73]
KS har psykisk helse som et emneord til undertema Helsetjenester. Difi har Psykisk helse som et undertema til Helse og omsorg.

**Comment by oystein-asnes** [comment]
Los 2.0 -temaet Psykisk helse består av disse emneordene:

- `Mobbing` (hva er tjenesten? Fjernes?)
- `Pedagogisk-psykologisk tjeneste` (ligger under Skole og utdanning)
- `Psykisk helsevern` (Psykisk helse er foreslått som eget emneord)
- `Rustiltak` (er dekket av temaet rusomsorg)
- `Spillavhengighet` (ikke dekket)

**Løsningsforslag**: 
- [ ] Fjerne `Psykisk helse` som eget undertema 
- [ ] Opprette `Psykisk helse` som eget emneord under `Helsetjenester`
- [ ] Flytte `Spillavhengighet` til `Helsetjenester`

**Comment by stephanie-lovenskiold** [comment]
Enig og det ser veldig bra ut. Men sliter litt med at Spillavhengighet kommer under Helsetjenester. Kan vi plassere det under Rusomsorg? Dessuten, er det en statlig eller kommunal tjeneste? Hva med alkoholisme og spiseforstyrrelser da?
Hvis vi kan endre Rusomsorg til Rus og avhengighet så synes jeg at Spillavhengighet passer bedre der  enn under helsetjenester. Og da kan vi få inn andre avhengigheter også, hvis det skulle bli aktuelt. Men jeg er fortsatt usikker på hva som er tjenesten.

**Comment by oystein-asnes** [comment]
Støtter forslaget om å endre undertemaet `Rusomsorg `til `Rus og avhengighet`. Da gjenåpner jeg #71

**Comment by oystein-asnes** [comment]
**Nytt løsningsforslag**:

- [ ] Fjerne `Psykisk helse` som eget undertema
- [ ] Endre `Psykisk helsevern` til `Psykisk helse` og legge det under `Helsetjenester`
- [ ] `Rusomsorg` ender navn til `Rus og avhengighet` #69 
- [ ] Flytte Spillavhengighet  (ikke Spill**e**avhengighet til `Rus og avhengighet`
