### ISSUE TITLE
[tema]Priser og gebyrer under Bygg og eiendom

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#74]
Er relatert til:

**Beskrivelse** 

**Løsningsforslag**  Priser og gebyrer blir til Priser og gebyrer for bygg og eiendom.

Emneordet Betalingssatser blir til Betalingssatser for kommunale tjenester

Emneordet Gebyrer/Gebyrregulativ blir til Gebyrer for byggesak.

**Comment by Elianne** [comment]
Endra emneord frå GebyrER til Gebyr (fleirtalsform)
