### ISSUE TITLE
Forslag utvidelse med EU-temaet "Internasjonale temaer"

### ISSUE THREAD

**Issue by lillelars** [difi/los#75]
Vi trenger mulighet for å tagge datasett med EU-temaet "Internasjonale temaer". 
Foreslår derfor å utvide LOS med følgende struktur:

Hovedkategori | Underkategori | Emneord
-- | -- | --
Skole og utdanning | Høyere utdanning | Studieutveksling
Internasjonalt | Utveksling | Studieutveksling
  |   |  
  | Politikk | EU
  |   | Nordisk Samarbeid
  |   |  
  | Bistand | U-hjelp
  |   | Nødhjelp

**Comment by oystein-asnes** [comment]
Denne er relatert til #93

**Comment by oystein-asnes** [comment]
@lillelars Vi ser behovet for å dekke gapet mellom EUs Data theme vocabulary og Los. Vi har utsatt denne typen utvidelser til v 3.1 (som vi ruller ut i mars/april 2020)

**Comment by oystein-asnes** [comment]
`Studieutveksling `kan opprettes som nytt emneord (se #445 ) . `Bistand `og `Politikk `går utover Los sitt  omfang  (offentlige tjenester). Behovet må dekkes av andre vokabularer. Når disse er publisert i SKOS-format kan Los uttrykke relasjoner til disse. Forslaget avvises.
