### ISSUE TITLE
[tema] Oppdatere "Trafikk og transport"

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#77]
Er relatert til: #60 

**Beskrivelse** 
Endringer knyttet til temaet Trafikk og transport (var: Trafikk, reiser og samferdsel)

**Løsningsforslag**
Konklusjon: Temaet skifter navn til "Trafikk og transport". Forslaget til SVV legges til grunn for undertema og emneord:  https://docs.google.com/spreadsheets/d/1llKIldetOMDRBqC5XlgE3mQqzU2OefoKxxQttzMa6rU/edit?usp=sharing

|  **Undertema** | **Emneord** |
| --- | --- |
|  Båt |  |
|   | Båtplass<br/>Havn<br/>Kystforvaltning<br/>Sjøfart<br/>Sjøsikkerhet |
|  Havn og kyst |  |
|   |  |
|  Luftfart |  |
|   | Fly (splitt)<br/>Helikopter (splitt)<br/>Lufthavn (alt: Flyplass) (ny)<br/>Drone (ny) |
|  Førerkort og sertifikat |  |
|   | "Båtførerbevis<br/>Båtsertifikat (ta ut?)<br/>Flysertifikat<br/>Førerkort<br/>Kjøreseddel<br/>Truckførerbevis" |
|  Kjøretøy |  |
|   | Los:<br/>Elbil<br/>Heftelser i motorvogn<br/>Kjøretøykontroll<br/>Kontrollmerke<br/>Motroferdsel i utmark<br/>Motorvognavgifter<br/>Piggdekk<br/>Registrering av kjøretøy<br/>Vrakpant<br/>KS:<br/>Elbil<br/>Piggdekk<br/>Snøskuter<br/>Vannskuter<br/>Vrakpant |
|   | Et eller annet om miljøvennlige kjøretøy |
|  Transporttilbud |  |
|   | Hidden labels: Transporttjenester, Kollektivtransport<br/>Los 2.0:<br/>Kameratkjøring<br/>Miljøvennlig transport<br/>Reisebillett<br/>Reisegaranti<br/>Ruteopplysning<br/>KS:<br/>Miljøvennlig transport<br/>Reisebillett<br/>Reisegaranti<br/>Ruteopplysning |
|   | Multimodal travel information services |
|  Veg |  |
|   | Brøyting<br/>Bompenger<br/>Feiing og strøing<br/>Gangvei<br/>Gatelys<br/>Gravemelding<br/>Miljøvennlig transport --> Denne bør over til vegtrafikk<br/>Parkering<br/>Skoleskyss<br/>Sykkel<br/>Tilrettelagt transport<br/>Trafikkinformasjon --> Denne bør over til vegtrafikk<br/>Veibygging<br/>Veivedlikehold |
|   | Ruteplan |
|  Yrkestransport |  |
|   | Hidden label: Godstransport<br/>Persontransport (Fjerne til fordel for transporttilbud)<br/>Nye:<br/>Rasteplasser <br/>Hviletider<br/>Kontroller (må finne bedre) <br/>Regler for godstransport<br/>(SVV kommer tilbake med mer) |
|  Vegtrafikk | TBD |

**Comment by oystein-asnes** [comment]
@klakegg Undertemaene "Båt" og "Havn og kyst" er uferdige. Har du forslag?

**Comment by oystein-asnes** [comment]
Fritidsskippersertifikat og Internasjonalt båtsertifikat (ICC) bør tilføyes temaet Førerkort og sertifikat

**Comment by stephanie-lovenskiold** [comment]
Beskrivelse til Båtplass mangler på bm
Beskrivelse til Havn mangler på bm og nn
Beskrivelse til kystforvaltning mangler på bm
Beskrivelse til Sjøfart mangler på bm
Beskrivelse til Sjøsikkerhet mangler på bm
Beskrivelse til Internasjonalt båtsertifikat mangler på bm
Beskrivelse til Kjøreseddel mangler på bm og nn
Beskrivelse til Truckførerbevis mangler på bm
Beskrivelse til Flysertifikat mangler på bm
Beskrivelse til Førerkort mangler på bm
Beskrivelse til kameratkjøring mangler på bm
Beskrivelse til Miljøvennlig transport mangler på bm og nn
Beskrivelse til Reisegaranti mangler på bm
Beskrivelse til elbil mangler på bm og nn
Beskr til Heftelser i motorvogn mangler på bm
Beskr til Kjøretøykontroll mangler på bm
Beskr til Motorferdsel i utmark mangler på bm
Beskr til Motorvognavgifter mangler på bm
Beskr til Piggdekk mangler på bm
Beskr til Registrering av kjøretøy mangler på bm
Beskr til Gangveg mangler på bm og nn


Ikke lagt inn i koden:
Kontrollmerke (hører til Kjøretøy)
Feiing og strøing (hører til veg)

**Comment by oystein-asnes** [comment]
Vi avventer nytt forslag fra SVV og Entur før vi gjør mer med dette temaet.
