### ISSUE TITLE
[tema] Endre Veg og vegtrafikk til Veg (og videre til Veg og vegregulering)

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#79]
Er relatert til: #77 

**Beskrivelse** 
Temaet splittes i to tema: Veg og Vegtrafikk
**Løsningsforslag**
Følgende emneord knyttes til undertemaet Veg;
Brøyting
Bompenger
Feiing og strøing
Gangvei
Gatelys
Gravemelding
Parkering
Sykkel
Vegbygging
Vegvedlikehold

Disse flyttes til vegtrafikk:
Miljøvennlig transport 
Trafikkinformasjon 
Trafikksikkerhet 

Disse knyttes til transporttilbud:
Ruteplanlegger
Skoleskyss
Tilrettelagt transport

**Comment by oystein-asnes** [comment]
Vurdere nyy navn: Veg og vegtjenester (Road and road services)

**Comment by oystein-asnes** [comment]
Aksellastrestriksjoner er ny knyttet til Veg - i tillegg til emneordene over

**Comment by oystein-asnes** [comment]
Ruteplanlegger er flyttet til Transporttilbud

**Comment by oystein-asnes** [comment]
Skoleskyss er flytte til Transporttilbud

**Comment by oystein-asnes** [comment]
Sykkel mangler definisjon (hva er tjenesten?)

**Comment by oystein-asnes** [comment]
Tilrettelagt transport er flytte til Transporttilbud

**Comment by stephanie-lovenskiold** [comment]
Skal Transporttilbud erstatte kollektivtilbud?

**Comment by oystein-asnes** [comment]
Etter ønske fra SVV og Entur skal det gjøres følgende endringer:
- `Veg` endres til `Veg og vegregulering`
- `Kollektivtilbud` endres til `Mobilitetstilbud` (transporttilbud er alternativ tittel)
- `Vegtrafikk` endres til `Trafikkinformasjon` (følgefeil: undertemaet "Trafikkinformasjon" må endre navn eller fjernes) `Vegtrafikk` legges til som HiddelLabel
