### ISSUE TITLE
[ord] Forslag om å fjerne Godstransport og Persontransport som emneord bør vurderes på nytt

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#80]
Er relatert til: #77 
**Beskrivelse:**

[`Persontransport`](http://psi.norge.no/los/3/ord/persontransport.html) og [`Godstransport`](http://psi.norge.no/los/3/ord/godstransport.html) er i Los 2.0 egne emneord, men er v 3.0 foreslått omgjort til skjulte søkeord til [`Yrkestransport`](http://psi.norge.no/los/3/tema/yrkestransport.html). `Yrkestransport `må i så fall endres fra tema til emneord.

**Skjulte søkeord for Persontransport er:**
- Buss
- Drosjeløyve
- Enkeltturtillatelse
- Fellesskapslisens
- Limousin
- Passasjertransport
- Selskapsvognløyve
- Taxi
- Transportbevilling
- Transportløyve
- Turbil
- Turbuss
- Turvognløyve

**Skjulte søkeord for Godstransport er:**
- Enkeltturtillatelse
- Fellesskapstillatelse
- Godsløyve
- Spesialtransport
- Transportbevilling
- Transportløyve
- Tungtransport
- Vegliste

Her må SVV m fl. vurdere...
- om noen av disse skjulte søkeordene skal endres til egne emneord 
- om noen av disse skjulte søkeordene skal flyttes til emneordet `Yrkestransport`

**Comment by hildea** [comment]
Godt spørsmål. I denne omgangen går vi for å beholde dem som de er (dvs. beholde Godstransport og Persontransport under Yrkestransport), så får vi heller se på endring av dette seinere.

**Comment by oystein-asnes** [comment]
Vi har nå både `Godstransport `og `Frakt og logistikk` (forslag jf G-sheet) inne på lista. Skal vi ha begge?
