### ISSUE TITLE
[tema] Oppdatere Friluftsliv

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#83]
Er relatert til: #64 

**Beskrivelse** 
Legge til beskrivelser for eksisterende emneord og opprette nytt emneord "turløyper"

**Comment by stephanie-lovenskiold** [comment]
Åpnet denne igjen for vi trenger å ta stilling til emneordene (Los 2)
- Badeplass
- Fritidsutstyr
- Sykkel
Alle de andre emneordene har fått beskrivelser, så de er OK.
