### ISSUE TITLE
[tema] Oppdatere "Fritid"

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#84]
Er relatert til: #64 

**Beskrivelse** 
Legge til "Seniortilbud" jf forslag fra KS.

**Comment by stephanie-lovenskiold** [comment]
Finne ut hva vi skal gjøre med ordene Kjæledyr og sportsdyr og Musikk- og kulturskole.

**Comment by oystein-asnes** [comment]
Ser nå at jeg har lagt til Seniortilbud, men ikkje har fått med meg at det skal erstatte Eldresenter. Me fix :-)
