### ISSUE TITLE
[tema] Oppdatere Idrett

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#85]
Er relatert til: #64 

**Beskrivelse** 
Legge til emneordet "Svømmehall" jf innspill fra KS.

Legges til selv om Svømmehall åpenbart er en instans av undertemaet Idrettsanlegg. Løses eventuelt ved innføring av 4 nivåer.

**Comment by oystein-asnes** [comment]
Svømmehall er nå lagt til, men beskrivelsen kunne kanskje vært bedre? Av og til er det vel skolene som har disse anleggene og dermed treffer ikke "Idrettsanlegg med svømmebasseng" helt? Du får vurdere @stephanie-lovenskiold

**Comment by stephanie-lovenskiold** [comment]
Kanskje endre beskrivelsen til noe sånt som "svømmehaller er åpne for publikum til visse tider og kan være åpne for utleie". Vet at kommunene ønsker å ha den som eget ord fordi de får utrolig mange telefoner som spør om åpningstider.

**Comment by stephanie-lovenskiold** [comment]
Sjekket og OK
