### ISSUE TITLE
[tema] Oppdatere "Tilskudd til kultur, idrett og fritid"

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#87]
Er relatert til:  #64 (og #63)  

**Beskrivelse** 
Opprette "Tilskudd til helse og eldre" + "Tilskudd til tro og livssyn"

**Comment by oystein-asnes** [comment]
Lagt til med noen endringer jf forslaget til KS: "Helse og eldre" er endret til "Tilskudd til helse og eldre", "Tro og livssyn" er endret til "Tilskudd til..." Merk at også definisjonen er noe endret: Var "Kommunale midler..." -> endret til "Offentlige midler...".

**Comment by oystein-asnes** [comment]
Obs: I tittel er det brukt helse, mens i definisjonen er det bruke folkehelse: Offentlige midler som skal støtte lag, foreninger og organisasjoner til å drive aktiviteter rettet mot folkehelse og eldre. @stephanie-lovenskiold får vurdere om det skal stå slik.

**Comment by oystein-asnes** [comment]
Denne kan lukkes om du er enig med valgene som er gjort, @stephanie-lovenskiold

**Comment by stephanie-lovenskiold** [comment]
Fint. Da har jeg har gjort de samme endringene i Excel-filen. Tror det er ok å beholde ordet helse framfor folkehelse i Tilskudd til helse og eldre. Da stenger vi ikke for noe, og det er ikke så ofte innbyggere bruker ordet folkehelse.

**Comment by stephanie-lovenskiold** [comment]
Sjekket og OK

**Comment by stephanie-lovenskiold** [comment]
Øystein, ser at du har lagt inn Tilskudd til friluftsliv som ord under tema Friluftsliv. Fra før av ligger den som ord under tema Tilskudd til kultur, idrett og fritid. Er det meningen å ha den to ganger i samme temastruktur? Personlig synes jeg ikke det er nødvendig.
