### ISSUE TITLE
[tema] Endre navn på "Barnevern og familievern" til "Barnevern og foreldrestøtte" 

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#9]

**Comment by oystein-asnes** [comment]
Krever oppdatering av relasjoner for følgende tema:

http://psi.norge.no/los/ord/barnevern
http://psi.norge.no/los/ord/besoekshjem
http://psi.norge.no/los/ord/familievern
http://psi.norge.no/los/ord/fosterhjem
http://psi.norge.no/los/ord/overgrep
http://psi.norge.no/los/ord/tvangsekteskap

**Comment by oystein-asnes** [comment]
Engelsk pref label er ikke oppdatert. Er fortsatt "Child and family welfare"

**Comment by stephanie-lovenskiold** [comment]
Sjekket og OK
