### ISSUE TITLE
[ord] Opprette Ytelser til foreldre og foresatte

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#92]
Er relatert til: #91 

Beskrivelse: Opprette nytt emneord "Ytelser til foreldre og foresatte" og legge følgende eksisterende emneord til som skjulte søkeord (HiddenLabel):

Barnebidrag
Barnetrygd
Engangsstønad
Foreldrepenger
Kontantstøtte
Omsorgspenger
Stønad til enslig forsørger

Nye hjelpeord:
Bidragsforskudd * (Nytt hjelpeord)

**Comment by oystein-asnes** [comment]
Har lagt til følgende definisjon: "Økonomiske ytelser i forbindelse med det å ha barn." Noen bedre? @stephanie-lovenskiold ?

**Comment by stephanie-lovenskiold** [comment]
Som definisjon høres det veldig bra ut.
