### ISSUE TITLE
[tema] Mapping til EUs "Data Theme"-vokabular

### ISSUE THREAD

**Issue by oystein-asnes** [difi/los#93]
Er relatert til:

**Beskrivelse** 
Som til tilbyder av en nasjonal datakatalog ønsker jeg at temastrukturen i Los lar seg mappe mest mulig 1-til-1 til EUs kategorisering av data(sett) slik at vi slipper å bruke to vokabular med overlappende meningsinnhold når vi skal klassifisere datasett. 

**Løsningsforslag**
Dette kan gjøres direkte i Skos-koden i Los ved å referere til EUs Data Theme ved hjelp av skos:exactMatch og ev.  skos:closeMatch. I arbeidet med revisjon av Los bør en se til EUs "Data Theme" (https://publications.europa.eu/s/mCuy) slik at mappingen kan gjøres så konsistent som mulig. 

Mapping mellom Los 2.0 og Eus "Data Theme" finnes her: https://docs.google.com/spreadsheets/d/1Q6ufKGj4oGhSxJMmKY60_crTEr3HYq5HUlx2MmrGCk4/edit?usp=sharing

**Comment by oystein-asnes** [comment]
Selve mappingtabellen er i tillegg foreslått inn som en del av DCAT-AP-NO standarden

**Comment by oystein-asnes** [comment]
Det er fire temaer som det ikke er mulig å mappe fra Los 3.0 til EUs "Data theme":  `Vitenskap og teknologi` , `Internasjonale temaer`, `Økonomi og finans`, `Forvaltning og offentlig sektor`.

**Comment by oystein-asnes** [comment]
Her er mitt forslag til mapping av Los mot EUs [Data Theme](https://publications.europa.eu/s/mCuy). Kom gjerne med innspill @stigbd,  @klakegg  m.fl
<table>
  <tr>
   <td><strong>LOS -tema</strong>
   </td>
   <td><strong>match</strong>
   </td>
   <td><strong>Eu Data theme</strong>
   </td>
  </tr>
  <tr>
   <td>n/a
   </td>
   <td>n/a
   </td>
   <td>Forvaltning og offentlig sektor
   </td>
  </tr>
  <tr>
   <td>Natur, klima og miljø
   </td>
   <td>skos:closeMatch
   </td>
   <td>Miljø
   </td>
  </tr>
  <tr>
   <td>Landbruk
   </td>
   <td>skos:broadMatch
   </td>
   <td>Jordbruk, fiskeri, skogbruk og mat
   </td>
  </tr>
  <tr>
   <td>Bygg og eiendom
   </td>
   <td>skos:broadMatch
   </td>
   <td>Regioner og byer
   </td>
  </tr>
  <tr>
   <td>Familie og barn
   </td>
   <td>skos:broadMatch
   </td>
   <td>Befolkning og samfunn
   </td>
  </tr>
  <tr>
   <td>Kultur, idrett og fritid
   </td>
   <td>skos:broadMatch
   </td>
   <td>Utdanning, kultur og sport
   </td>
  </tr>
  <tr>
   <td>Skole og utdanning
   </td>
   <td>skos:broadMatch
   </td>
   <td>Utdanning, kultur og sport
   </td>
  </tr>
  <tr>
   <td>Trafikk, reiser og samferdsel
   </td>
   <td>skos:closeMatch
   </td>
   <td>Transport
   </td>
  </tr>
  <tr>
   <td>n/a
   </td>
   <td>n/a
   </td>
   <td>Økonomi og finans
   </td>
  </tr>
  <tr>
   <td>Helse og omsorg
   </td>
   <td>skos:narrowMatch
   </td>
   <td>Helse
   </td>
  </tr>
  <tr>
   <td>Lov og rett
   </td>
   <td>skos:broadMatch
   </td>
   <td>Justis, rettssystem og allmenn sikkerhet
   </td>
  </tr>
  <tr>
   <td>Samfunnssikkerhet og beredskap
   </td>
   <td>skos:broadMatch
   </td>
   <td>Justis, rettssystem og allmenn sikkerhet
   </td>
  </tr>
  <tr>
   <td>Energi
   </td>
   <td>skos:exactMatch
   </td>
   <td>Energi
   </td>
  </tr>
  <tr>
   <td>n/a
   </td>
   <td>n/a
   </td>
   <td>Internasjonale temaer
   </td>
  </tr>
  <tr>
   <td>n/a
   </td>
   <td>n/a
   </td>
   <td>Vitenskap og teknologi
   </td>
  </tr>
</table>

**Comment by oystein-asnes** [comment]
Mappingen er nå kvalitetssikret av @klakegg og vi legger inn alle mappinger som vi har match på i Los. De øvrige temaene (Forvaltning og offentlig sektor, Økonomi og finans, Internasjonale temaer og Vitenskap og teknologi) må løses i senere versjoner. (de ligger utenfor dagens omfang).

**Comment by Elianne** [comment]
Trafikk, reiser og samferdsel er ikke et tema/ord i LOS. Mener du Trafikk og transport? @oystein-asnes
