### ISSUE TITLE
[tema] Næring - må diskuteres

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#95]
Er relatert til:
#56 
Beskrivelse
Til diskusjon om hva vi skal gjøre med kategorien næring, må vi huske kommunenes ansvar for næringstuvikling. Blant annet er det mange tilskudd som tildeles forskjellige næringer.
I Los 2.0 har vi undertemaet Næringsutvikling. 
Relatert er også kommunale ordninger for landbruk, skogbruk og fiske (siste er jeg usikker på)

**Comment by stephanie-lovenskiold** [comment]
I KS' forslag heter det Næring og skatt. Temaet skal nå hete kun Næring.
Skatt skal bli eget hovedtema og tas bort fra Næring
Undertema skatt og avgift blir emneord Næringsskatt
Undertema Næring blir Næringsliv. Vi diskuterte også bedrift/næringsutvikling, men besluttet Næringsliv.
Emneord som skal under Næringsutvikling: arbeidsgiveravgift, eiendomsskatt, skatteattest
Etablering av barnehage fjernes fra Familie og barn/Barnehage
Næringsområder skal hete Næringsklynger
Emneordet Skatt blir Næringsskatt
Næringsfond skal legges til som emneord under Næringsliv
Tilsyn og kontroll med næringsvirksomhet blir til: Tilsyn med næringsliv.

Strukturen vil da bli:
**Næring**
Landbruk
- Erstatningsordninger
- Landbrukseiendom
- Plantevern
- Skogbruk
- Veterinær

Næringsliv
- Arbeidsgiveravgift
- Bedriftsetablering
- Bevilling og tillatelser
- Eiendomsskatt
- Etablering av barnehager
- Film- og videokonsesjon
- Miljøsertifisering
- Næringsfond
- Næringsklynger
- Næringsskatt
- Skatteattest
- Tilsyn med næringsliv

Tilskuddsordninger for næring
- Avløsningstilskudd
- Jordbrukstilskudd
- Produksjonstilskudd
- Skogbrukstilskudd
- Støtte til bedrifter
- Tilskudd til økologisk landbruk

**Comment by oystein-asnes** [comment]
Næringsskatt skal fjernes. Skatteetaten løser denne i "neste versjon"

**Comment by Elianne** [comment]
Erstatningsordninger finnes allerede som tema. Oppretter emneord `Erstatningsordninger i landbruket`. OK? @stephanie-lovenskiold @oystein-asnes

**Comment by oystein-asnes** [comment]
>Skatt skal bli eget hovedtema og tas bort fra Næring

`Skatt `er undertema under `Skatt og avgift`. Hvorfor vil du ha dette som et hovudtema @stephanie-lovenskiold ? Forslaget er i konflikt med [Skatteetaten sitt forslag](http://psi.norge.no/los/3/tema/skatt-og-avgift.html).

 >Undertema Skatt og avgift blir emneord Næringsskatt

Også dette er i konflikt med Skatteetaten sitt forslag. Vi kan opprette `Næringsskatt` som eget emneord, men det må i så fall knyttes til `Skatt og avgift`  (`Skatt og avgift` -> `Skatt` -> **`Næringsskatt`**). Det kan ikke erstatte  `Skatt og avgift (som er et hovudtema)

>Emneordet Skatt blir Næringsskatt

Foreslår å avvise forslaget. `Skatt `er et undertema og jeg foreslår` Næringsskatt` som emneord jf over

>Erstatningsordninger

Her må vi vurdere å bli mer spesifikke (samme problemstilling som "mobbing"). `Erstatningsordninger i landbruket` kanskje?   Emneordet må spesifiseres (beskivelse, engelsk osb)

**Comment by Elianne** [comment]
@stephanie-lovenskiold Mangler også definisjoner på følgende emneord:  
- Avløsningstilskudd
 - Jordbrukstilskudd
 - Produksjonstilskudd
 - Skogbrukstilskudd
 - Støtte til bedrifter
 - Tilskudd til økologisk landbruk

**Comment by oystein-asnes** [comment]
Merk at `Erstatningsordninger` også er et undertema under `Lov og rett`. Vi kan ikke samtidig ha det som et emneord. http://psi.norge.no/los/3/tema/erstatningsordninger.html

**Comment by oystein-asnes** [comment]
En (teknisk) mulig løsning er å ikke ha med `Skatt og avgift` i samlingen Kommune-los, men gå rett på nivå 2 (`Skatt`). Dermed vil dette temaet kun få to nivåer for kommunene. Det blir kanskje litt rart men passer bra ut fra at kommunene ikkje driver med avgifter (?)

**Comment by stephanie-lovenskiold** [comment]
Definisjoner (ikke kvalitetssikret)

Avløsningstilskudd
Avløysartilskot
Farm assistance grant
Avløserordningene   er en del av velferdsordningene i landbruket. Husdyrbrukere skal få avløsing   ved ferier, sykdom o.l.
Avløysarordningane   er ein del av velferdsordningane i landbruket. Husdyrbrukarar skal få   avløysing ved feriar, sjukdom o.l.
--

Jordbrukstilskudd
Jordbrukstilskot
Farming   grants
Fellesbetegnelse   for tilskudd til spesielle formål innenfor jordbruk.
Fellesnamn   for tilskot til spesielle formål innanfor jordbruk.
--
Produksjonstilskudd
Produksjonstilskot
Produce   grants
Fellesbetegnelse   for en rekke tilskuddsordninger i landbruket.
Fellesnamn   for ei rekkje tilskotsordningar i landbruket.
--
Skogbrukstilskudd
Skogbrukstilskot
Forestry grants
Tilskuddsordninger for skogbrukere.
Tilskotsordningar   for skogbrukarar.
--
Støtte   til bedrifter
Stønad   til bedrifter
Support   for businesses
Etablerertilskudd   og annen støtte til bedrifter.
Etablerertilskot   og annan stønad til bedrifter.
--
Tilskudd   til økologisk landbruk
Tilskot   til økologisk landbruk
Support   for businesses
Etablerertilskudd   og annen støtte til bedrifter.
Etablerertilskot   og annan stønad til bedrifter.

**Comment by stephanie-lovenskiold** [comment]
Øystein, vet ikke om jeg skjønte det du sa om skatt. Vi kan ta det opp i morgen :)

**Comment by Elianne** [comment]
> Tilskudd til økologisk landbruk

Her er det vel feil definisjon (og engelsk term - eg la inn Support for organic farming).

**Comment by oystein-asnes** [comment]
> Erstatningsordninger finnes allerede som tema. Oppretter emneord `Erstatningsordninger i landbruket`. OK? @stephanie-lovenskiold @oystein-asnes

`Erstatningsordninger i landbruket` opprettes og knyttes kun til `Næring `->`Landbruk`
`Naturskadeerstatning` (eksisterer) knyttes til `Eiendom`

**Comment by oystein-asnes** [comment]
**Løsningsforslag:**
Næringsutvikling = Aktiviteter som det offentlige gjør for å tiltrekke seg aktivitet i sin geografi/domene/mm
Næringsliv = Resten 
@stephanie-lovenskiold plasserer inn emneordene i de to kategoriene. Denne saken lukkes og ny opprettes for Næringsliv og Næringsutvikling

**Comment by stephanie-lovenskiold** [comment]
`Tilskudd til økologisk landbruk`

@Elianne, her er det som er riktig:
Tilskudd til økologisk landbruk
Tilskot til økologisk landbruk
Organic agriculture grants
Fellesbetegnelse for tilskudd til de som driver økologisk landbruk.
Fellesnamn for tilskot til dei som driv økologisk landbruk.
