### ISSUE TITLE
[tema] Behov for å skille Helse og Omsorg i to temaer

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#96]
Er relatert til:
#46, #70 
**Beskrivelse** 
EU og andre land bruker Helse for seg. Kun norske kommuner setter Helse og omsorg sammen. Det er ønske om at vi skal følge EU-standardene.
**Løsningsforslag**
Se om vi kan lage to temaer; Helse og Omsorg. Sjekk hvilke emneord som vi evt må legge begge steder eller endre på annet vis.

**Comment by stephanie-lovenskiold** [comment]
Vi ble enige om denne strukturen
**Helse**
Akutt hjelp
Folkehelse
Helsetjenester
Svangerskap og fødsel
Pasientrettigheter

**Omsorg**
Avlastning og støtte
Hjemmetjenester
Rusomsorg

Vi ble enige om å lage et nytt undertema som heter Hjelpemidler. Under omsorg?

**Comment by oystein-asnes** [comment]
I arbeidsmøte 05.09.2019 ble det tatt en kontrabeslutning om å slå sammen Helse og omsorg til ett tema i tråd med KS sitt forslag.
