### ISSUE TITLE
[tema] Fjerne botilbud fra Botilbud og sosiale tjenester.

### ISSUE THREAD

**Issue by stephanie-lovenskiold** [difi/los#97]
Er relatert til:
#68 
**Beskrivelse** 
Botilbud fjernes fra tittel 
**Løsningsforslag**
Vi har Botilbud og sosiale tjenester som alternativ tittel. Dette for å dekke behovet til kommunen om å synliggjøre tilbudet.

**Comment by stephanie-lovenskiold** [comment]
Det må vi diskutere nærmere, for det kan bli misvisende at temaet heter Pensjon og sosiale tjenester, når staten yter det ene og kommunen det andre. Hvis en kommune ønsker å bruke Los som en menystruktur kan det bli dumt. For innbygger vil ikke finne noe om pensjon under den 'knappen'

**Comment by oystein-asnes** [comment]
Lukkes.  Overlapper delvis med #228
